export * as hrmTypes from "./hrm";
export * as InventoryTypes from "./inventory";
export * as  ExpenseTypes from "./finance";
export * as adminCouponTypes from "./admin-coupon";
export * as customerTypes from "./customer";
export * as NotificationTypes from "./notification-template";
export * as giftCardTypes from "./gift-card";
export * as loyaltyTypes from "./loyalty-point";
export * as loyaltyPointHistoryTypes from "./loyalty-point-history";
export * as AdminMailSettingsTypes from "./mail-settings";
export * as PaymentSettingsTypes from "./payment-settings";
export * as purchaseTypes from "./purchase";
export * as supplierTypes from "./supplier";
export * as purchaseOrderTypes from "./purchase-order";
export * as purchaseReturnTypes from "./purchase-return";
export * as ReportTypes from "./Reports";
export * as RolePermissionTypes from "./rolespermission";
export * as storeTypes from "./Store";
export * as taxTypes from "./Tax";
export * as StockTypes from "./stock"
export * as SalesTypes from "./sales";
export * as InvoiceDesignTypes from "./invoice-design";

