import type { AnnualReport } from "@/types/admin/Reports";

// Get current year as default
const currentYear = new Date().getFullYear();

const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const annualData = 
{
data:[
  // Main Store - Current Year
  {
    id: "1",
    month: "January",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 125000,
    totalPurchases: 75000,
    totalExpenses: 15000,
    netProfit: 35000,
    growthPercentage: 5.2,
  },
  {
    id: "2",
    month: "February",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 135000,
    totalPurchases: 80000,
    totalExpenses: 16000,
    netProfit: 39000,
    growthPercentage: 8.0,
  },
  {
    id: "3",
    month: "March",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 145000,
    totalPurchases: 85000,
    totalExpenses: 17000,
    netProfit: 43000,
    growthPercentage: 7.4,
  },
  {
    id: "4",
    month: "April",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 140000,
    totalPurchases: 82000,
    totalExpenses: 16500,
    netProfit: 41500,
    growthPercentage: -3.4,
  },
  {
    id: "5",
    month: "May",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 150000,
    totalPurchases: 88000,
    totalExpenses: 18000,
    netProfit: 44000,
    growthPercentage: 7.1,
  },
  {
    id: "6",
    month: "June",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 155000,
    totalPurchases: 90000,
    totalExpenses: 19000,
    netProfit: 46000,
    growthPercentage: 3.3,
  },
  {
    id: "7",
    month: "July",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 160000,
    totalPurchases: 92000,
    totalExpenses: 20000,
    netProfit: 48000,
    growthPercentage: 3.2,
  },
  {
    id: "8",
    month: "August",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 158000,
    totalPurchases: 91000,
    totalExpenses: 19500,
    netProfit: 47500,
    growthPercentage: -1.2,
  },
  {
    id: "9",
    month: "September",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 165000,
    totalPurchases: 95000,
    totalExpenses: 21000,
    netProfit: 49000,
    growthPercentage: 4.4,
  },
  {
    id: "10",
    month: "October",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 170000,
    totalPurchases: 98000,
    totalExpenses: 22000,
    netProfit: 50000,
    growthPercentage: 3.0,
  },
  {
    id: "11",
    month: "November",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 175000,
    totalPurchases: 100000,
    totalExpenses: 23000,
    netProfit: 52000,
    growthPercentage: 2.9,
  },
  {
    id: "12",
    month: "December",
    year: currentYear,
    storeId: "1",
    storeName: "Main Store",
    totalSales: 180000,
    totalPurchases: 105000,
    totalExpenses: 24000,
    netProfit: 51000,
    growthPercentage: 2.8,
  },
  // Branch Store - Current Year
  {
    id: "13",
    month: "January",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 95000,
    totalPurchases: 55000,
    totalExpenses: 12000,
    netProfit: 28000,
    growthPercentage: 4.5,
  },
  {
    id: "14",
    month: "February",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 100000,
    totalPurchases: 58000,
    totalExpenses: 13000,
    netProfit: 29000,
    growthPercentage: 5.2,
  },
  {
    id: "15",
    month: "March",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 105000,
    totalPurchases: 60000,
    totalExpenses: 13500,
    netProfit: 31500,
    growthPercentage: 5.0,
  },
  {
    id: "16",
    month: "April",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 102000,
    totalPurchases: 59000,
    totalExpenses: 13200,
    netProfit: 29800,
    growthPercentage: -2.8,
  },
  {
    id: "17",
    month: "May",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 108000,
    totalPurchases: 62000,
    totalExpenses: 14000,
    netProfit: 32000,
    growthPercentage: 5.8,
  },
  {
    id: "18",
    month: "June",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 110000,
    totalPurchases: 63000,
    totalExpenses: 14500,
    netProfit: 32500,
    growthPercentage: 1.8,
  },
  {
    id: "19",
    month: "July",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 112000,
    totalPurchases: 64000,
    totalExpenses: 15000,
    netProfit: 33000,
    growthPercentage: 1.8,
  },
  {
    id: "20",
    month: "August",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 111000,
    totalPurchases: 63500,
    totalExpenses: 14800,
    netProfit: 32700,
    growthPercentage: -0.8,
  },
  {
    id: "21",
    month: "September",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 115000,
    totalPurchases: 66000,
    totalExpenses: 15500,
    netProfit: 33500,
    growthPercentage: 3.6,
  },
  {
    id: "22",
    month: "October",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 118000,
    totalPurchases: 68000,
    totalExpenses: 16000,
    netProfit: 34000,
    growthPercentage: 2.6,
  },
  {
    id: "23",
    month: "November",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 120000,
    totalPurchases: 69000,
    totalExpenses: 16500,
    netProfit: 34500,
    growthPercentage: 1.6,
  },
  {
    id: "24",
    month: "December",
    year: currentYear,
    storeId: "2",
    storeName: "Branch Store",
    totalSales: 122000,
    totalPurchases: 70000,
    totalExpenses: 17000,
    netProfit: 35000,
    growthPercentage: 1.6,
  },
],
totalData:24,
}





