import type { CustomerReport } from "@/types/admin/Reports";

export const customerDataDummy: CustomerReport[] = [
  {
    id: "CUST-001",
    customerCode: "C001",
    customerName: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "+1-555-0101",
    totalOrders: 18,
    totalSpent: 2450.5,
    averageOrderValue: 136.14,
    lastPurchaseDate: "2024-12-05",
    firstPurchaseDate: "2023-03-15",
    daysSinceLastPurchase: 25,
    loyaltyPoints: 320,
    totalReturns: 1,
    returnAmount: 85.3,
    preferredPaymentMethod: "Card",
    city: "New York",
    state: "NY",
    country: "USA",
    gender: "Female",
  },
  {
    id: "CUST-002",
    customerCode: "C002",
    customerName: "Brian Carter",
    email: "brian.carter@example.com",
    phone: "+1-555-0102",
    totalOrders: 9,
    totalSpent: 980.75,
    averageOrderValue: 109,
    lastPurchaseDate: "2024-11-22",
    firstPurchaseDate: "2023-06-10",
    daysSinceLastPurchase: 38,
    loyaltyPoints: 180,
    totalReturns: 0,
    returnAmount: 0,
    preferredPaymentMethod: "UPI",
    city: "Austin",
    state: "TX",
    country: "USA",
    gender: "Male",
  },
  {
    id: "CUST-003",
    customerCode: "C003",
    customerName: "Catherine Lee",
    email: "catherine.lee@example.com",
    phone: "+1-555-0103",
    totalOrders: 25,
    totalSpent: 3120.25,
    averageOrderValue: 124.81,
    lastPurchaseDate: "2025-01-12",
    firstPurchaseDate: "2022-12-01",
    daysSinceLastPurchase: 8,
    loyaltyPoints: 510,
    totalReturns: 2,
    returnAmount: 140.5,
    preferredPaymentMethod: "Card",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    gender: "Female",
  },
  {
    id: "CUST-004",
    customerCode: "C004",
    customerName: "David Smith",
    email: "david.smith@example.com",
    phone: "+1-555-0104",
    totalOrders: 6,
    totalSpent: 540,
    averageOrderValue: 90,
    lastPurchaseDate: "2024-10-30",
    firstPurchaseDate: "2024-02-18",
    daysSinceLastPurchase: 61,
    loyaltyPoints: 95,
    totalReturns: 1,
    returnAmount: 40,
    preferredPaymentMethod: "Cash",
    city: "Chicago",
    state: "IL",
    country: "USA",
    gender: "Male",
  },
  {
    id: "CUST-005",
    customerCode: "C005",
    customerName: "Emma Davis",
    email: "emma.davis@example.com",
    phone: "+1-555-0105",
    totalOrders: 14,
    totalSpent: 1685.35,
    averageOrderValue: 120.38,
    lastPurchaseDate: "2024-12-28",
    firstPurchaseDate: "2023-08-09",
    daysSinceLastPurchase: 2,
    loyaltyPoints: 260,
    totalReturns: 0,
    returnAmount: 0,
    preferredPaymentMethod: "Wallet",
    city: "Seattle",
    state: "WA",
    country: "USA",
    gender: "Female",
  },
  {
    id: "CUST-006",
    customerCode: "C006",
    customerName: "Felix Turner",
    email: "felix.turner@example.com",
    phone: "+1-555-0106",
    totalOrders: 20,
    totalSpent: 2210.9,
    averageOrderValue: 110.55,
    lastPurchaseDate: "2024-09-14",
    firstPurchaseDate: "2023-01-20",
    daysSinceLastPurchase: 107,
    loyaltyPoints: 410,
    totalReturns: 3,
    returnAmount: 215.75,
    preferredPaymentMethod: "Card",
    city: "Denver",
    state: "CO",
    country: "USA",
    gender: "Male",
  },
  {
    id: "CUST-007",
    customerCode: "C007",
    customerName: "Grace Kim",
    email: "grace.kim@example.com",
    phone: "+1-555-0107",
    totalOrders: 11,
    totalSpent: 1280,
    averageOrderValue: 116.36,
    lastPurchaseDate: "2025-01-05",
    firstPurchaseDate: "2023-11-30",
    daysSinceLastPurchase: 15,
    loyaltyPoints: 205,
    totalReturns: 1,
    returnAmount: 60,
    preferredPaymentMethod: "Card",
    city: "Boston",
    state: "MA",
    country: "USA",
    gender: "Female",
  },
  {
    id: "CUST-008",
    customerCode: "C008",
    customerName: "Harold Green",
    email: "harold.green@example.com",
    phone: "+1-555-0108",
    totalOrders: 7,
    totalSpent: 715.6,
    averageOrderValue: 102.23,
    lastPurchaseDate: "2024-08-19",
    firstPurchaseDate: "2024-04-02",
    daysSinceLastPurchase: 133,
    loyaltyPoints: 120,
    totalReturns: 0,
    returnAmount: 0,
    preferredPaymentMethod: "Cash",
    city: "Miami",
    state: "FL",
    country: "USA",
    gender: "Male",
  },
  {
    id: "CUST-009",
    customerCode: "C009",
    customerName: "Isabella Martinez",
    email: "isabella.martinez@example.com",
    phone: "+1-555-0109",
    totalOrders: 16,
    totalSpent: 1840.45,
    averageOrderValue: 115.03,
    lastPurchaseDate: "2024-11-30",
    firstPurchaseDate: "2022-10-12",
    daysSinceLastPurchase: 30,
    loyaltyPoints: 330,
    totalReturns: 2,
    returnAmount: 150,
    preferredPaymentMethod: "UPI",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    gender: "Female",
  },
  {
    id: "CUST-010",
    customerCode: "C010",
    customerName: "Jason Brown",
    email: "jason.brown@example.com",
    phone: "+1-555-0110",
    totalOrders: 4,
    totalSpent: 360,
    averageOrderValue: 90,
    lastPurchaseDate: "2024-07-25",
    firstPurchaseDate: "2024-05-03",
    daysSinceLastPurchase: 158,
    loyaltyPoints: 60,
    totalReturns: 0,
    returnAmount: 0,
    preferredPaymentMethod: "Card",
    city: "Phoenix",
    state: "AZ",
    country: "USA",
    gender: "Male",
  },
  {
    id: "CUST-011",
    customerCode: "C011",
    customerName: "Kylie Nguyen",
    email: "kylie.nguyen@example.com",
    phone: "+1-555-0111",
    totalOrders: 13,
    totalSpent: 1525.8,
    averageOrderValue: 117.37,
    lastPurchaseDate: "2025-01-09",
    firstPurchaseDate: "2023-07-14",
    daysSinceLastPurchase: 11,
    loyaltyPoints: 245,
    totalReturns: 1,
    returnAmount: 75.2,
    preferredPaymentMethod: "Wallet",
    city: "Portland",
    state: "OR",
    country: "USA",
    gender: "Female",
  },
  {
    id: "CUST-012",
    customerCode: "C012",
    customerName: "Liam Patel",
    email: "liam.patel@example.com",
    phone: "+1-555-0112",
    totalOrders: 22,
    totalSpent: 2755.4,
    averageOrderValue: 125.25,
    lastPurchaseDate: "2024-12-18",
    firstPurchaseDate: "2022-09-25",
    daysSinceLastPurchase: 12,
    loyaltyPoints: 480,
    totalReturns: 2,
    returnAmount: 130,
    preferredPaymentMethod: "Card",
    city: "Dallas",
    state: "TX",
    country: "USA",
    gender: "Male",
  },
];
