import type { DailyCashierReport } from "@/types/admin/Reports";

// Get today's date as default
const today = new Date();
const todayStr = today.toISOString().split("T")[0];

export const dailyCashierData: DailyCashierReport[] = [
  {
    id: "1",
    date: todayStr,
    staffName: "John Doe",
    posId: "POS001",
    counterId: "C001",
    totalBills: 45,
    netSales: 12500.5,
    amountReceived: 12500.5,
    changeGiven: 0,
    cashInHand: 500,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "2",
    date: todayStr,
    staffName: "Jane Smith",
    posId: "POS002",
    counterId: "C002",
    totalBills: 38,
    netSales: 9800.25,
    amountReceived: 10000,
    changeGiven: 199.75,
    cashInHand: 750,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "3",
    date: todayStr,
    staffName: "Bob Johnson",
    posId: "POS003",
    counterId: "C003",
    totalBills: 52,
    netSales: 15200.75,
    amountReceived: 15200.75,
    changeGiven: 0,
    cashInHand: 600,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "4",
    date: todayStr,
    staffName: "Alice Brown",
    posId: "POS001",
    counterId: "C001",
    totalBills: 42,
    netSales: 11200,
    amountReceived: 11500,
    changeGiven: 300,
    cashInHand: 800,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "5",
    date: todayStr,
    staffName: "Charlie Wilson",
    posId: "POS004",
    counterId: "C004",
    totalBills: 35,
    netSales: 8900.5,
    amountReceived: 8900.5,
    changeGiven: 0,
    cashInHand: 550,
    storeId: "3",
    storeName: "HQ Store",
  },
  {
    id: "6",
    date: todayStr,
    staffName: "Diana Prince",
    posId: "POS002",
    counterId: "C002",
    totalBills: 48,
    netSales: 13400.25,
    amountReceived: 13700,
    changeGiven: 299.75,
    cashInHand: 700,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "7",
    date: todayStr,
    staffName: "Edward Norton",
    posId: "POS003",
    counterId: "C003",
    totalBills: 41,
    netSales: 10800,
    amountReceived: 10800,
    changeGiven: 0,
    cashInHand: 650,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "8",
    date: todayStr,
    staffName: "Fiona Green",
    posId: "POS004",
    counterId: "C004",
    totalBills: 39,
    netSales: 10200.75,
    amountReceived: 10500,
    changeGiven: 299.25,
    cashInHand: 600,
    storeId: "3",
    storeName: "HQ Store",
  },
  // Previous day data
  {
    id: "9",
    date: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    staffName: "John Doe",
    posId: "POS001",
    counterId: "C001",
    totalBills: 43,
    netSales: 11800.5,
    amountReceived: 11800.5,
    changeGiven: 0,
    cashInHand: 500,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "10",
    date: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    staffName: "Jane Smith",
    posId: "POS002",
    counterId: "C002",
    totalBills: 36,
    netSales: 9200.25,
    amountReceived: 9500,
    changeGiven: 299.75,
    cashInHand: 750,
    storeId: "1",
    storeName: "Main Store",
  },
];

