import type { PayrollReport } from "@/types/admin/Reports";

// Get last month
const now = new Date();
const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
const lastMonthName = lastMonth.toLocaleString("default", { month: "long" });
const lastMonthYear = lastMonth.getFullYear();

export const payrollData: PayrollReport[] = [
  {
    id: "1",
    staffName: "John Doe",
    storeName: "Main Store",
    fixedSalary: 5000,
    totalWorkingDays: 22,
    presentDays: 20,
    totalPayableAmount: 4545.45,
    payout: "Paid",
    month: lastMonthName,
    year: lastMonthYear,
    bankAccount: "****1234",
  },
  {
    id: "2",
    staffName: "Jane Smith",
    storeName: "Main Store",
    fixedSalary: 4500,
    totalWorkingDays: 22,
    presentDays: 22,
    totalPayableAmount: 4500.0,
    payout: "Paid",
    month: lastMonthName,
    year: lastMonthYear,
    bankAccount: "****5678",
  },
  {
    id: "3",
    staffName: "Bob Johnson",
    storeName: "Branch Store",
    fixedSalary: 4000,
    totalWorkingDays: 22,
    presentDays: 18,
    totalPayableAmount: 3272.73,
    payout: "Pending",
    month: lastMonthName,
    year: lastMonthYear,
    bankAccount: "****9012",
  },
  {
    id: "4",
    staffName: "Alice Brown",
    storeName: "Branch Store",
    fixedSalary: 4200,
    totalWorkingDays: 22,
    presentDays: 21,
    totalPayableAmount: 4009.09,
    payout: "Paid",
    month: lastMonthName,
    year: lastMonthYear,
    bankAccount: "****3456",
  },
  {
    id: "5",
    staffName: "Charlie Wilson",
    storeName: "HQ Store",
    fixedSalary: 5500,
    totalWorkingDays: 22,
    presentDays: 19,
    totalPayableAmount: 4750.0,
    payout: "Pending",
    month: lastMonthName,
    year: lastMonthYear,
    bankAccount: "****7890",
  },
  {
    id: "6",
    staffName: "Diana Prince",
    storeName: "Main Store",
    fixedSalary: 4800,
    totalWorkingDays: 22,
    presentDays: 22,
    totalPayableAmount: 4800.0,
    payout: "Paid",
    month: lastMonthName,
    year: lastMonthYear,
    bankAccount: "****2468",
  },
  {
    id: "7",
    staffName: "Edward Norton",
    storeName: "Branch Store",
    fixedSalary: 3800,
    totalWorkingDays: 22,
    presentDays: 20,
    totalPayableAmount: 3454.55,
    payout: "Failed",
    month: lastMonthName,
    year: lastMonthYear,
    bankAccount: "****1357",
  },
  {
    id: "8",
    staffName: "Fiona Green",
    storeName: "HQ Store",
    fixedSalary: 5200,
    totalWorkingDays: 22,
    presentDays: 21,
    totalPayableAmount: 4963.64,
    payout: "Paid",
    month: lastMonthName,
    year: lastMonthYear,
    bankAccount: "****8642",
  },
  // Previous month data
  {
    id: "9",
    staffName: "John Doe",
    storeName: "Main Store",
    fixedSalary: 5000,
    totalWorkingDays: 21,
    presentDays: 19,
    totalPayableAmount: 4523.81,
    payout: "Paid",
    month: new Date(now.getFullYear(), now.getMonth() - 2, 1).toLocaleString("default", { month: "long" }),
    year: new Date(now.getFullYear(), now.getMonth() - 2, 1).getFullYear(),
    bankAccount: "****1234",
  },
  {
    id: "10",
    staffName: "Jane Smith",
    storeName: "Main Store",
    fixedSalary: 4500,
    totalWorkingDays: 21,
    presentDays: 21,
    totalPayableAmount: 4500.0,
    payout: "Paid",
    month: new Date(now.getFullYear(), now.getMonth() - 2, 1).toLocaleString("default", { month: "long" }),
    year: new Date(now.getFullYear(), now.getMonth() - 2, 1).getFullYear(),
    bankAccount: "****5678",
  },
];

