import type { PurchaseTaxReport } from "@/types/admin/Reports";

// Get today's date and previous dates
const today = new Date();
const getDateString = (daysAgo: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split("T")[0];
};

export const purchaseTaxData: PurchaseTaxReport[] = [
  {
    id: "1",
    date: getDateString(0),
    supplier: "Tech Supplies Inc.",
    supplierNo: "GSTIN-29ABCDE1234F1Z5",
    invoiceNo: "PO-2024-001",
    items: "Laptop × 10, Mouse × 50",
    taxableValue: 5000,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 500,
    purchaseType: "Taxable",
    totalAmount: 5500,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "2",
    date: getDateString(0),
    supplier: "Global Electronics",
    supplierNo: "VAT-12345678",
    invoiceNo: "PO-2024-002",
    items: "Keyboard × 30, Monitor × 5",
    taxableValue: 7500,
    taxType: "Inclusive",
    taxRate: 8.5,
    taxAmount: 637.5,
    purchaseType: "Taxable",
    totalAmount: 8137.5,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "3",
    date: getDateString(1),
    supplier: "Office Depot Pro",
    supplierNo: "GSTIN-27FGHIJ5678K2L6",
    invoiceNo: "PO-2024-003",
    items: "Tablet × 20, Case × 40",
    taxableValue: 12000,
    taxType: "Reverse",
    taxRate: 10,
    taxAmount: 1200,
    purchaseType: "Taxable",
    totalAmount: 13200,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "4",
    date: getDateString(1),
    supplier: "Warehouse Solutions",
    supplierNo: "VEND-001234",
    invoiceNo: "PO-2024-004",
    items: "Headphones × 25",
    taxableValue: 3000,
    taxType: "NA",
    taxRate: 0,
    taxAmount: 0,
    purchaseType: "Non-Taxable",
    totalAmount: 3000,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "5",
    date: getDateString(2),
    supplier: "Tech Supplies Inc.",
    supplierNo: "GSTIN-29ABCDE1234F1Z5",
    invoiceNo: "PO-2024-005",
    items: "Smartphone × 15, Charger × 15",
    taxableValue: 8500,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 850,
    purchaseType: "Taxable",
    totalAmount: 9350,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "6",
    date: getDateString(2),
    supplier: "Global Electronics",
    supplierNo: "VAT-12345678",
    invoiceNo: "PO-2024-006",
    items: "USB Cable × 100, Adapter × 20",
    taxableValue: 6000,
    taxType: "Inclusive",
    taxRate: 8.5,
    taxAmount: 510,
    purchaseType: "Taxable",
    totalAmount: 6510,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "7",
    date: getDateString(3),
    supplier: "Office Depot Pro",
    supplierNo: "GSTIN-27FGHIJ5678K2L6",
    invoiceNo: "PO-2024-007",
    items: "Printer × 5, Paper × 50",
    taxableValue: 15000,
    taxType: "Reverse",
    taxRate: 10,
    taxAmount: 1500,
    purchaseType: "Taxable",
    totalAmount: 16500,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "8",
    date: getDateString(3),
    supplier: "Warehouse Solutions",
    supplierNo: "VEND-001234",
    invoiceNo: "PO-2024-008",
    items: "Webcam × 10",
    taxableValue: 4000,
    taxType: "NA",
    taxRate: 0,
    taxAmount: 0,
    purchaseType: "Non-Taxable",
    totalAmount: 4000,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "9",
    date: getDateString(4),
    supplier: "Tech Supplies Inc.",
    supplierNo: "GSTIN-29ABCDE1234F1Z5",
    invoiceNo: "PO-2024-009",
    items: "SSD × 20, RAM × 40",
    taxableValue: 7200,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 720,
    purchaseType: "Taxable",
    totalAmount: 7920,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "10",
    date: getDateString(4),
    supplier: "Global Electronics",
    supplierNo: "VAT-12345678",
    invoiceNo: "PO-2024-010",
    items: "Speaker × 20, Stand × 10",
    taxableValue: 9800,
    taxType: "Inclusive",
    taxRate: 8.5,
    taxAmount: 833,
    purchaseType: "Taxable",
    totalAmount: 10633,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "11",
    date: getDateString(5),
    supplier: "Office Depot Pro",
    supplierNo: "GSTIN-27FGHIJ5678K2L6",
    invoiceNo: "PO-2024-011",
    items: "Laptop Stand × 30",
    taxableValue: 11000,
    taxType: "Reverse",
    taxRate: 10,
    taxAmount: 1100,
    purchaseType: "Taxable",
    totalAmount: 12100,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "12",
    date: getDateString(5),
    supplier: "Warehouse Solutions",
    supplierNo: "VEND-001234",
    invoiceNo: "PO-2024-012",
    items: "Cable Organizer × 50",
    taxableValue: 2500,
    taxType: "NA",
    taxRate: 0,
    taxAmount: 0,
    purchaseType: "Non-Taxable",
    totalAmount: 2500,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "13",
    date: getDateString(6),
    supplier: "Tech Supplies Inc.",
    supplierNo: "GSTIN-29ABCDE1234F1Z5",
    invoiceNo: "PO-2024-013",
    items: "External HDD × 10, Enclosure × 10",
    taxableValue: 9500,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 950,
    purchaseType: "Taxable",
    totalAmount: 10450,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "14",
    date: getDateString(6),
    supplier: "Global Electronics",
    supplierNo: "VAT-12345678",
    invoiceNo: "PO-2024-014",
    items: "Power Bank × 20, Cable × 30",
    taxableValue: 6800,
    taxType: "Inclusive",
    taxRate: 8.5,
    taxAmount: 578,
    purchaseType: "Taxable",
    totalAmount: 7378,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "15",
    date: getDateString(7),
    supplier: "Office Depot Pro",
    supplierNo: "GSTIN-27FGHIJ5678K2L6",
    invoiceNo: "PO-2024-015",
    items: "Gaming Mouse × 10, Pad × 10",
    taxableValue: 13000,
    taxType: "Reverse",
    taxRate: 10,
    taxAmount: 1300,
    purchaseType: "Taxable",
    totalAmount: 14300,
    storeId: "2",
    storeName: "Branch Store",
  },
];
