import type { SalesTaxReport } from "@/types/admin/Reports";

// Get today's date and previous dates
const today = new Date();
const getDateString = (daysAgo: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split("T")[0];
};

export const salesTaxData: SalesTaxReport[] = [
  {
    id: "1",
    date: getDateString(0),
    invoiceNo: "INV-2024-001",
    items: "Laptop × 2, Mouse × 5",
    taxableValue: 1000,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 100,
    saleType: "Taxable",
    totalAmount: 1100,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "2",
    date: getDateString(0),
    invoiceNo: "INV-2024-002",
    items: "Keyboard × 3, Monitor × 1",
    taxableValue: 1500,
    taxType: "Inclusive",
    taxRate: 8.5,
    taxAmount: 127.5,
    saleType: "Taxable",
    totalAmount: 1627.5,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "3",
    date: getDateString(1),
    invoiceNo: "INV-2024-003",
    items: "Tablet × 1, Case × 2",
    taxableValue: 2500,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 250,
    saleType: "Taxable",
    totalAmount: 2750,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "4",
    date: getDateString(1),
    invoiceNo: "INV-2024-004",
    items: "Headphones × 2",
    taxableValue: 800,
    taxType: "NA",
    taxRate: 0,
    taxAmount: 0,
    saleType: "Non-Taxable",
    totalAmount: 800,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "5",
    date: getDateString(2),
    invoiceNo: "INV-2024-005",
    items: "Smartphone × 1, Charger × 1",
    taxableValue: 3200,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 320,
    saleType: "Taxable",
    totalAmount: 3520,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "6",
    date: getDateString(2),
    invoiceNo: "INV-2024-006",
    items: "USB Cable × 10, Adapter × 2",
    taxableValue: 1200,
    taxType: "Inclusive",
    taxRate: 8.5,
    taxAmount: 102,
    saleType: "Taxable",
    totalAmount: 1302,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "7",
    date: getDateString(3),
    invoiceNo: "INV-2024-007",
    items: "Printer × 1, Paper × 5",
    taxableValue: 4500,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 450,
    saleType: "Taxable",
    totalAmount: 4950,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "8",
    date: getDateString(3),
    invoiceNo: "INV-2024-008",
    items: "Webcam × 1",
    taxableValue: 600,
    taxType: "NA",
    taxRate: 0,
    taxAmount: 0,
    saleType: "Non-Taxable",
    totalAmount: 600,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "9",
    date: getDateString(4),
    invoiceNo: "INV-2024-009",
    items: "SSD × 2, RAM × 4",
    taxableValue: 1800,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 180,
    saleType: "Taxable",
    totalAmount: 1980,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "10",
    date: getDateString(4),
    invoiceNo: "INV-2024-010",
    items: "Speaker × 2, Stand × 1",
    taxableValue: 2200,
    taxType: "Inclusive",
    taxRate: 8.5,
    taxAmount: 187,
    saleType: "Taxable",
    totalAmount: 2387,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "11",
    date: getDateString(5),
    invoiceNo: "INV-2024-011",
    items: "Laptop Stand × 3",
    taxableValue: 3500,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 350,
    saleType: "Taxable",
    totalAmount: 3850,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "12",
    date: getDateString(5),
    invoiceNo: "INV-2024-012",
    items: "Cable Organizer × 5",
    taxableValue: 950,
    taxType: "NA",
    taxRate: 0,
    taxAmount: 0,
    saleType: "Non-Taxable",
    totalAmount: 950,
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "13",
    date: getDateString(6),
    invoiceNo: "INV-2024-013",
    items: "External HDD × 1, Enclosure × 1",
    taxableValue: 2800,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 280,
    saleType: "Taxable",
    totalAmount: 3080,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "14",
    date: getDateString(6),
    invoiceNo: "INV-2024-014",
    items: "Power Bank × 2, Cable × 3",
    taxableValue: 1400,
    taxType: "Inclusive",
    taxRate: 8.5,
    taxAmount: 119,
    saleType: "Taxable",
    totalAmount: 1519,
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "15",
    date: getDateString(7),
    invoiceNo: "INV-2024-015",
    items: "Gaming Mouse × 1, Pad × 1",
    taxableValue: 5000,
    taxType: "Exclusive",
    taxRate: 10,
    taxAmount: 500,
    saleType: "Taxable",
    totalAmount: 5500,
    storeId: "2",
    storeName: "Branch Store",
  },
];
