import type { SalesReport } from "@/types/admin/Reports";

export const salesDataDummy: SalesReport[] = [
  {
    id: "1",
    code: "PT001",
    productName: "Lenovo 3rd Generation",
    category: "Computers",
    soldQty: 20,
    salesAmount: 1000,
    availableStockQty: 100,
    paymentMethod: "Credit Card",
    date: "2024-01-15",
    storeId: "1",
    storeName: "Gadget World",
  },
  {
    id: "2",
    code: "PT002",
    productName: "Bold V3.2",
    category: "Accessories",
    soldQty: 15,
    salesAmount: 1200,
    availableStockQty: 150,
    paymentMethod: "Cash",
    date: "2024-01-15",
    storeId: "1",
    storeName: "Gadget World",
  },
  {
    id: "3",
    code: "PT003",
    productName: "Nike Jordan",
    category: "Shoe",
    soldQty: 18,
    salesAmount: 2000,
    availableStockQty: 170,
    paymentMethod: "Bank Transfer",
    date: "2024-01-16",
    storeId: "2",
    storeName: "Fashion Store",
  },
  {
    id: "4",
    code: "PT004",
    productName: "Apple Series 5 Watch",
    category: "Accessories",
    soldQty: 25,
    salesAmount: 300,
    availableStockQty: 120,
    paymentMethod: "Debit Card",
    date: "2024-01-16",
    storeId: "1",
    storeName: "Gadget World",
  },
  {
    id: "5",
    code: "PT005",
    productName: "Samsung Galaxy S21",
    category: "Mobile",
    soldQty: 12,
    salesAmount: 800,
    availableStockQty: 80,
    paymentMethod: "Digital Wallet",
    date: "2024-01-17",
    storeId: "2",
    storeName: "Fashion Store",
  },
  {
    id: "6",
    code: "PT006",
    productName: "MacBook Pro M2",
    category: "Computers",
    soldQty: 8,
    salesAmount: 2500,
    availableStockQty: 45,
    paymentMethod: "Credit Card",
    date: "2024-01-17",
    storeId: "1",
    storeName: "Gadget World",
  },
];

