import type { StockHistoryReport } from "@/types/admin/Reports";

// Get today's date and previous dates
const today = new Date();
const getDateString = (daysAgo: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split("T")[0];
};

export const stockHistoryData: StockHistoryReport[] = [
  // Add Stock transactions (from purchases/manual additions)
  {
    id: "1",
    date: getDateString(0),
    storeName: "Main Store",
    productName: "Laptop Dell XPS 15",
    category: "Electronics",
    subCategory: "Computers",
    method: "Add Stock",
    stockBefore: 5,
    stockAfter: 15,
    handledBy: "John Doe",
    variantName: "16GB RAM, 512GB SSD",
    storeId: "1",
  },
  {
    id: "2",
    date: getDateString(0),
    storeName: "Main Store",
    productName: "Monitor 27 inch",
    category: "Electronics",
    subCategory: "Displays",
    method: "Add Stock",
    stockBefore: 12,
    stockAfter: 20,
    handledBy: "John Doe",
    variantName: "4K UHD",
    storeId: "1",
  },
  {
    id: "3",
    date: getDateString(1),
    storeName: "Main Store",
    productName: "Webcam HD 1080p",
    category: "Electronics",
    subCategory: "Peripherals",
    method: "Add Stock",
    stockBefore: 0,
    stockAfter: 15,
    handledBy: "John Doe",
    storeId: "1",
  },
  {
    id: "4",
    date: getDateString(5),
    storeName: "Branch Store",
    productName: "RAM 16GB DDR4",
    category: "Electronics",
    subCategory: "Components",
    method: "Add Stock",
    stockBefore: 5,
    stockAfter: 25,
    handledBy: "John Doe",
    storeId: "2",
  },
  {
    id: "5",
    date: getDateString(6),
    storeName: "Branch Store",
    productName: "Laptop Stand",
    category: "Accessories",
    subCategory: "Desk Accessories",
    method: "Add Stock",
    stockBefore: 3,
    stockAfter: 15,
    handledBy: "John Doe",
    variantName: "Aluminum",
    storeId: "2",
  },
  
  // Adjustment transactions (stock corrections)
  {
    id: "6",
    date: getDateString(1),
    storeName: "Main Store",
    productName: "Keyboard Mechanical",
    category: "Accessories",
    subCategory: "Input Devices",
    method: "Adjustment",
    stockBefore: 15,
    stockAfter: 13,
    handledBy: "Admin User",
    variantName: "RGB Backlit",
    storeId: "1",
  },
  {
    id: "7",
    date: getDateString(4),
    storeName: "Main Store",
    productName: "SSD 1TB",
    category: "Electronics",
    subCategory: "Storage",
    method: "Adjustment",
    stockBefore: 10,
    stockAfter: 9,
    handledBy: "Admin User",
    storeId: "1",
  },
  
  // Transfer transactions (stock moved between stores)
  {
    id: "8",
    date: getDateString(4),
    storeName: "Main Store",
    productName: "Wireless Mouse",
    category: "Accessories",
    subCategory: "Input Devices",
    method: "Transfer",
    stockBefore: 20,
    stockAfter: 15,
    handledBy: "John Doe",
    storeId: "1",
  },
  {
    id: "9",
    date: getDateString(2),
    storeName: "Main Store",
    productName: "USB Cable Type-C",
    category: "Accessories",
    method: "Transfer",
    stockBefore: 50,
    stockAfter: 40,
    handledBy: "John Doe",
    storeId: "1",
  },
  
  // Return transactions (customer returns - stock added back)
  {
    id: "10",
    date: getDateString(3),
    storeName: "Main Store",
    productName: "Headphones Wireless",
    category: "Accessories",
    subCategory: "Audio",
    method: "Return",
    stockBefore: 8,
    stockAfter: 9,
    handledBy: "Admin User",
    variantName: "Noise Cancelling",
    storeId: "1",
  },
  {
    id: "11",
    date: getDateString(1),
    storeName: "Main Store",
    productName: "Laptop Dell XPS 15",
    category: "Electronics",
    subCategory: "Computers",
    method: "Return",
    stockBefore: 13,
    stockAfter: 14,
    handledBy: "Jane Smith",
    variantName: "32GB RAM, 1TB SSD",
    storeId: "1",
  },
  
  // Damage transactions (damaged items removed)
  {
    id: "12",
    date: getDateString(4),
    storeName: "Main Store",
    productName: "SSD 1TB",
    category: "Electronics",
    subCategory: "Storage",
    method: "Return",
    stockBefore: 9,
    stockAfter: 8,
    handledBy: "Admin User",
    storeId: "1",
  },
  {
    id: "13",
    date: getDateString(2),
    storeName: "Main Store",
    productName: "Keyboard Mechanical",
    category: "Accessories",
    subCategory: "Input Devices",
    method: "Return",
    stockBefore: 13,
    stockAfter: 12,
    handledBy: "Admin User",
    variantName: "RGB Backlit",
    storeId: "1",
  },
  
  // Expiry transactions (expired items removed)
  {
    id: "14",
    date: getDateString(7),
    storeName: "Main Store",
    productName: "External HDD 2TB",
    category: "Electronics",
    subCategory: "Storage",
    method: "Expiry",
    stockBefore: 8,
    stockAfter: 6,
    handledBy: "Admin User",
    storeId: "1",
  },
  {
    id: "15",
    date: getDateString(5),
    storeName: "Branch Store",
    productName: "Power Bank 20000mAh",
    category: "Accessories",
    method: "Expiry",
    stockBefore: 15,
    stockAfter: 12,
    handledBy: "Admin User",
    storeId: "2",
  },
];
