import type { TransactionReport } from "@/types/admin/Reports";

export const transactionDataDummy: TransactionReport[] = [
  {
    id: "1",
    date: "2024-01-15",
    transactionId: "TXN-001-2024",
    productName: "Laptop Dell XPS 13",
    soldQty: 1,
    amount: 2500,
    discount: 100,
    loyaltyAmount: 50,
    taxes: 235,
    totalAmount: 2585,
    paymentMethod: "Credit Card",
    soldBy: "John Doe",
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "2",
    date: "2024-01-15",
    transactionId: "TXN-002-2024",
    productName: "Wireless Mouse",
    soldQty: 2,
    amount: 40,
    discount: 5,
    loyaltyAmount: 2,
    taxes: 3.3,
    totalAmount: 36.3,
    paymentMethod: "Cash",
    soldBy: "Jane Smith",
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "3",
    date: "2024-01-16",
    transactionId: "TXN-003-2024",
    productName: "Office Chair",
    soldQty: 1,
    amount: 300,
    discount: 20,
    loyaltyAmount: 10,
    taxes: 27,
    totalAmount: 297,
    paymentMethod: "Bank Transfer",
    soldBy: "Mike Johnson",
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "4",
    date: "2024-01-16",
    transactionId: "TXN-004-2024",
    productName: "Monitor 24 inch",
    soldQty: 1,
    amount: 200,
    discount: 15,
    loyaltyAmount: 5,
    taxes: 18,
    totalAmount: 198,
    paymentMethod: "Debit Card",
    soldBy: "John Doe",
    storeId: "1",
    storeName: "Main Store",
  },
  {
    id: "5",
    date: "2024-01-17",
    transactionId: "TXN-005-2024",
    productName: "Keyboard Mechanical",
    soldQty: 1,
    amount: 60,
    discount: 5,
    loyaltyAmount: 3,
    taxes: 5.2,
    totalAmount: 58.2,
    paymentMethod: "Digital Wallet",
    soldBy: "Jane Smith",
    storeId: "2",
    storeName: "Branch Store",
  },
  {
    id: "6",
    date: "2024-01-17",
    transactionId: "TXN-006-2024",
    productName: "Desk Lamp",
    soldQty: 2,
    amount: 60,
    discount: 8,
    loyaltyAmount: 4,
    taxes: 4.8,
    totalAmount: 56.8,
    paymentMethod: "Check",
    soldBy: "Mike Johnson",
    storeId: "1",
    storeName: "Main Store",
  },
];

