import { AdminTypes } from "@/types";

// Product Management
export const productheading = "Product Management"
export const productbio = "Manage your products across all stores"
export const addProduct = "Add Product"
export const bulkAddProduct = "+ Bulk Add Products"
export const finalProduct = "Product"
export const productname = "Product Name "
export const productdescription = "Product Description"
export const productsku = "SKU "
export const productbarcode = "Barcode"
export const productcategory = "Category"
export const productsubcategory = "Sub Category *"
export const productbrand = "Brand "
export const productprice = "Price "
export const addvariation = "Add Variation"
export const enablevariations = "Enable Variations"
export const productcostprice = "Cost Price "
export const productsellingprice = "Selling Price "
export const productquantity = "Quantity "
export const productminquantity = "Minimum Quantity"
export const productmaxquantity = "Maximum Quantity"
export const productunit = "Unit "
export const productweight = "Weight (kg)"
export const productdimensions = "Dimensions"
export const productstore = "Store "
export const selectstore = "Select Store"
export const selectcategory = "Select Category"
export const selectbrand = "Select Brand"
export const selectunit = "Select Unit"
export const productimage = "Product Image"
export const nameanddescription = "Name And Description"
export const productcategorylabel = "Product Category"
export const productsubcategorylabel = "Product Sub-Category"
export const selectsubcategory = "Select Sub-Category"
export const enterproductname = "Enter product name"
export const enterproductdescription = "Enter product description"
export const max150characters = "Maximum 150 Characters"
export const categorysection = "Category"
export const storeskustatus = "Store, SKU & Status"
export const storelabel = "Store"
export const skuaotolabel = "SKU (Auto Generated)"
export const entersku = "Enter SKU"
export const productdetails = "Product Details"
export const brandnamelabel = "Brand Name"
export const selecttax = "Select Tax"
export const productpricing = "Product Pricing"
export const taxlabel = "Tax"
export const discountlabel = "Discount"
export const percentagesymbol = "%"
export const expirydetails = "Expiry Details"
export const expirydate = "Expiry Date"
export const warrantystartdate = "Warranty Start Date"
export const warrantylabel = "Warranty"
export const selectwarranty = "Select Warranty"
export const productvariations = "Product Variations"
export const variationtype = "Variation Type"
export const variationvalue = "Variation Value"
export const actionslabel = "Actions"
export const selecttype = "Select Type"
export const selectvalue = "Select Value"
export const autogenerated = "Auto-generated"
export const updating = "Updating..."
export const updateLabel = "Update"
export const productinfo = "Product Information"
export const inventoryinfo = "Inventory Information"
export const pricinginfo = "Pricing Information"
export const storeinfo = "Store Information"
export const bulkproductinfo = "Bulk Product Information"
export const bulkaddproducts = "Bulk Add Products"
export const bulkadddescription = "Add multiple products at once using the form below"
export const addrow = "+ Add Row"
export const removerow = "Remove Row"
export const lowstock = "Low Stock"
export const outofstock = "Out of Stock"
export const instock = "In Stock"
export const regenerate = "Regenerate"
export const month = "Month"
export const year = "Year"
export const actions = "Actions"


// Product Category Management
export const categoryname = "Category Name"
export const title = "Category Management"
export const categorydescription = "Manage your product categories"
export const addModalTitle = "Add Category"
export const editModalTitle = "Edit Category"
export const tableTitle = "Categories"
export const totalCategories = "Total Categories"
export const activeCategories = "Active Categories"
export const inactiveCategories = "Inactive Categories"
export const recentCategories = "Recent Categories (7 days)"
export const descriptionColumn = "Description"
export const categorynamelabel = "Category Name "
export const categorynameplaceholder = "Enter category name"
export const descriptionPlaceholder = "Enter category description"
export const searchplaceholder = "Search by name, description, status, or dates..."
export const updatedSuccessfully = "Category updated successfully."
export const createdSuccessfully = "Category created successfully."
export const deletedSuccessfully = "The category has been deleted."
export const addFailed = "Failed to add category."
export const updateFailed = "Failed to update category."
export const deleteFailed = "Failed to delete category."
export const update = "Update"
export const processing = "Processing..."

// Sub Category Management

export const subcategoryStrings = {
  subcategoryheading: "Sub Category Management",
  subcategorybio: "Manage your product subcategories",
  addSubCategory: "Add Sub Category",
  bulkAddSubCategory: "+ Bulk Add Sub Categories",
  finalSubCategory: "Sub Category",
  subcategoryname: "Sub Category Name",
  subcategorydescription: "Sub Category Description",
  title: "Sub Category Management",
  description: "Manage your product subcategories",
  addButton: "Add Sub Category",
  addModalTitle: "Add Sub Category",
  editModalTitle: "Edit Sub Category",
  tableTitle: "Sub Categories",
  totalSubCategories: "Total Sub Categories",
  activeSubCategories: "Active Sub Categories",
  inactiveSubCategories: "Inactive Sub Categories",
  recentSubCategories: "Recent Sub Categories (7 days)",
  subCategoryProfileLabel: "Sub Category Profile",
  completeSubCategoryInformationAndDetailsLabel: "Complete sub category information and details",
  subCategoryInformationLabel: "Sub Category Information",
  subcategoryNameLabel: "Sub Category Name ",
  subCategoryNameLabel: "Sub Category Name",
  subCategoryCodeLabel: "Sub Category Code",
  descriptionLabel: "Description",
  categoryLabel: "Category ",
  codeLabel: "Sub Category Code ",
  imageLabel: "Sub Category Image",
  namePlaceholder: "Enter sub category name",
  codePlaceholder: "Enter sub category code",
  descriptionPlaceholder: "Enter sub category description",
  uploadImageLabel: "Upload Image",
  noCategoriesAvailable: "No categories available",
  saveSubCategory: "Save",
  searchPlaceholder: "Search by name, category, code, description, status, or dates...",
  updatedSuccessfully: "Sub Category updated successfully.",
  createdSuccessfully: "Sub Category added successfully",
  deletedSuccessfully: "The subcategory has been deleted.",
  addFailed: "Failed to add subcategory.",
  updateFailed: "Failed to update subcategory.",
  deleteFailed: "Failed to delete subcategory.",
  cancel: "Cancel",
  update: "Update",
  add: "Save",
  processing: "Processing...",
};

// Common Strings
export const descriptionlabel = "Description"
export const statuslabel = "Status"
export const requiredstar = "*"
export const add = "Add";
export const back = "Back";
export const backLabel = "Back";
export const create = "Create";
export const save = "Save"
export const saving = "Saving..."
export const cancel = "Cancel"
export const applyButtonLabel = "Apply";
export const editButtonLabel = "Edit";
export const sendEmailLabel = "Send Email";
export const pdfPrintLabel = "PDF/Print";
export const receiveButtonLabel = "Receive";
export const saveButtonLabel = "Save";
export const deleteButtonLabel = "Delete"
export const viewDetailsButtonLabel = "View Details"
export const shortdescriptionlabel = "Short Description "
export const shortdescription = "Short Description"
export const startDateLabel = "Start Date";
export const endDateLabel = "End Date";
export const createdOn = "Created On"
export const updatedOn = "Updated On"
export const allstatus = "All Status"
export const activestatus = "Active"
export const inactivestatus = "Inactive"
export const alltypes = "All Types"
export const fixed = "Fixed"
export const percentage = "Percentage"
export const phonelabel = "Phone No "
export const phone = "Phone Number"
export const emaillabel = "Email "
export const email = "Email"
export const passwordlabel = "Password "
export const password = "Password"
export const cancelbutton = "Cancel"
export const closebutton = "Close"
export const createddate = "Created Date"
export const lastupdated = "Last Updated"
export const saveallchanges = "Save All Changes"
export const upload = "Upload"
export const createdby = "Created By"

// Print Labels
export const printLabels = "Print Labels"
export const addProducts = "Add Products"
export const searchProducts = "Search products..."
export const selectedProducts = "Selected Products"
export const product = "Product"
export const labels = "Labels"
export const date = "Date"
export const group = "Group"
export const none = "None"
export const noProductsAddedYet = "No products added yet"
export const labelConfiguration = "Label Configuration"
export const productName = "Product Name"
export const incTax = "Inc. tax"
export const excTax = "Exc. tax"
export const twentyLabelsPerSheet = "20 Labels per Sheet"
export const thirtyLabelsPerSheet = "30 Labels per Sheet"
export const fortyLabelsPerSheet = "40 Labels per Sheet"
export const products = "products"
export const clearAllProducts = "Clear All"
export const preview = "Preview"

export const brandStrings = {
  title: "Brand Management",
  addButton: "Add Brand",
  addModalTitle: "Add New Brand",
  editModalTitle: "Edit Brand",
  tableTitle: "Brands",
  totalBrands: "Total Brands",
  activeBrands: "Active Brands",
  inactiveBrands: "Inactive Brands",
  recentBrands: "Recent Brands (7 days)"
};

export const unitStrings = {
  unitLabel: "Unit",
  shortNameLabel: "Short Name",
  title: "Unit Management",
  description: "Manage your product units",
  addButton: "Add Unit",
  addModalTitle: "Add New Unit",
  editModalTitle: "Edit Unit",
  tableTitle: "Units",
  totalUnits: "Total Units",
  activeUnits: "Active Units",
  inactiveUnits: "Inactive Units",
  unitProfileLabel: "Unit Profile",
  completeUnitInformationAndDetailsLabel: "Complete unit information and details",
  recentUnits: "Recent Units (7 days)",
  unitInformationLabel: "Unit Information",
  unitNameLabel: "Unit Name"
};

export const warrantyStrings = {
  warrantyInformationLabel: "Warranty Information",
  warrantyProfileLabel: "Warranty Profile",
  completeWarrantyInformationAndDetailsLabel: "Complete warranty information and details",
  durationPeriodLabel: "Duration Period",
  warrantyNameLabel: "Warranty Name",
  warrantyDescriptionLabel: "Warranty Description",
  title: "Warranty Management",
  description: "Manage your product warranties",
  addButton: "Add Warranty",
  addModalTitle: "Add New Warranty",
  editModalTitle: "Edit Warranty",
  tableTitle: "Warranties",
  totalWarranties: "Total Warranties",
  activeWarranties: "Active Warranties",
  inactiveWarranties: "Inactive Warranties",
  recentWarranties: "Recent Warranties (7 days)"
};

export const expiredStockStrings = {
  title: "Expired Stock Management",
  tableTitle: "Expired Stock",
  totalExpiredStock: "Total Expired Stock",
  description: "View and manage expired stock items"
};

export const variantStrings = {
  variantProfileLabel: "Variant Profile",
  completeVariantInformationAndDetailsLabel: "Complete variant information and details",
  variantInformationLabel: "Variant Information",
  noValuesLabel: "No values",
  valuesLabel: "Values",
  variantNameLabel: "Variant",
  title: "Variant Management",
  description: "Manage your product variants",
  addButton: "Add Variant",
  addModalTitle: "Add New Variant",
  editModalTitle: "Edit Variant",
  tableTitle: "Variants",
  totalVariants: "Total Variants",
  activeVariants: "Active Variants",
  inactiveVariants: "Inactive Variants",
  recentVariants: "Recent Variants (7 days)",
  multipleValuesNote: "Separate multiple values with commas. Example: Cotton, Polyester, Silk"
};

export const lowStockStrings = {
  title: "Low Stock Management",
  tableTitle: "Low Stock Items",
  totalLowStock: "Total Low Stock Items",
  description: "View and manage items with low stock levels"
};



// HRM Management
export const weekDays: AdminTypes.hrmTypes.commonTypes.WeekDay[] = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday"
];

export const designations = [
  "cashier",
  "manager",
];

// HRM Strings
export const hrmStrings = {
  title: "Human Resource Management",
  description: "Manage your staff, shifts, attendance, and leave requests",
  totalStaff: "Total Staff",
  activeStaff: "Active Staff",
  inactiveStaff: "Inactive Staff",
  recentStaff: "Recent Staff (7 days)",
  totalManagers: "Total Managers",
  activeManagers: "Active Managers",
  inactiveManagers: "Inactive Managers",
  recentManagers: "Recent Managers (7 days)",
  totalShifts: "Total Shifts",
  activeShifts: "Active Shifts",
  inactiveShifts: "Inactive Shifts",
  recentShifts: "Recent Shifts (7 days)",
  totalLeaveRequests: "Total Leave Requests",
  pendingLeaveRequests: "Pending Leave Requests",
  approvedLeaveRequests: "Approved Leave Requests",
  rejectedLeaveRequests: "Rejected Leave Requests",
  totalAttendance: "Total Attendance Records",
  presentToday: "Present Today",
  absentToday: "Absent Today",
  onLeaveToday: "On Leave Today",
};

export const staffStrings = {
  title: "Staff Management",
  description: "Manage your store staff members",
  addButton: "Add",
  addModalTitle: "Add New Staff",
  editModalTitle: "Edit Staff",
  tableTitle: "Staff Members",
  totalStaff: "Total Staff",
  activeStaff: "Active Staff",
  inactiveStaff: "Inactive Staff",
  recentStaff: "Recent Staff (7 days)",
  nameLabel: "Full Name ",
  emailLabel: "Email Address ",
  phoneLabel: "Phone Number ",
  designationLabel: "Designation ",
  storeLabel: "Store ",
  salaryLabel: "Salary ",
  joiningDateLabel: "Joining Date ",
  statusLabel: "Status ",
  imageLabel: "Profile Image",
  addressLabel: "Address",
  emergencyContactLabel: "Emergency Contact",
  namePlaceholder: "Enter full name",
  emailPlaceholder: "Enter email address",
  phonePlaceholder: "Enter phone number",
  designationPlaceholder: "Select designation",
  storePlaceholder: "Select store",
  salaryPlaceholder: "Enter salary amount",
  addressPlaceholder: "Enter address",
  emergencyContactPlaceholder: "Enter emergency contact",
  selectStore: "Select Store",
  selectDesignation: "Select Designation",
  updatedSuccessfully: "Staff member updated successfully.",
  deletedSuccessfully: "Staff member has been deleted.",
  addFailed: "Failed to add staff member.",
  updateFailed: "Failed to update staff member.",
  deleteFailed: "Failed to delete staff member.",
  cancel: "Cancel",
  update: "Update",
  add: "Add",
  processing: "Processing...",
};

export const managerStrings = {
  title: "Manager Management",
  description: "Manage your store managers",
  addButton: "Add Manager",
  addModalTitle: "Add New Manager",
  editModalTitle: "Edit Manager",
  tableTitle: "Managers",
  totalManagers: "Total Managers",
  activeManagers: "Active Managers",
  inactiveManagers: "Inactive Managers",
  recentManagers: "Recent Managers (7 days)",
  permissionsLabel: "Permissions",
  permissionsPlaceholder: "Select permissions",
  updatedSuccessfully: "Manager updated successfully.",
  deletedSuccessfully: "Manager has been deleted.",
  addFailed: "Failed to add manager.",
  updateFailed: "Failed to update manager.",
  deleteFailed: "Failed to delete manager.",
  cancel: "Cancel",
  update: "Update",
  add: "Add",
  processing: "Processing...",
};

export const shiftStrings = {
  title: "Shift Management",
  description: "Manage work shifts for your staff",
  addButton: "Add",
  addModalTitle: "Add",
  editModalTitle: "Edit",
  tableTitle: "Shifts",
  totalShifts: "Total Shifts",
  activeShifts: "Active Shifts",
  inactiveShifts: "Inactive Shifts",
  recentShifts: "Recent Shifts (7 days)",
  titleLabel: "Shift Title",
  startTimeLabel: "Start Time",
  endTimeLabel: "End Time",
  breakDurationLabel: "Break Duration (minutes)",
  branchLabel: "Branch",
  weekOffLabel: "Week Off Days",
  statusLabel: "Status",
  titlePlaceholder: "Enter shift title",
  startTimePlaceholder: "Select start time",
  endTimePlaceholder: "Select end time",
  breakDurationPlaceholder: "Enter break duration",
  branchPlaceholder: "Select branch",
  weekOffPlaceholder: "Select week off days",
  selectBranch: "Select Branch",
  selectWeekOff: "Select Week Off Days",
  updatedSuccessfully: "Shift updated successfully.",
  deletedSuccessfully: "Shift has been deleted.",
  addFailed: "Failed to add shift.",
  updateFailed: "Failed to update shift.",
  deleteFailed: "Failed to delete shift.",
  cancel: "Cancel",
  update: "Update",
  add: "Add",
  save: "Save",
  processing: "Processing...",
  shiftDetails: "Shift Details",
  shiftDetailsSubtitle: "Complete shift information and details",
  shiftInfo: "Shift Information",
  shiftTitle: "Shift Title",
  startTime: "Start Time",
  endTime: "End Time",
  breakDuration: "Break Duration",
};

export const shiftAssignmentStrings = {
  title: "Shift Assignment",
  description: "Assign shifts to staff members",
  addButton: "Assign Shift",
  addModalTitle: "Assign New Shift",
  editModalTitle: "Edit Shift Assignment",
  tableTitle: "Shift Assignments",
  totalAssignments: "Total Assignments",
  activeAssignments: "Active Assignments",
  completedAssignments: "Completed Assignments",
  recentAssignments: "Recent Assignments (7 days)",
  shiftLabel: "Shift",
  staffLabel: "Staff",
  dateLabel: "Date",
  branchLabel: "Branch",
  startTimeLabel: "Start Time",
  endTimeLabel: "End Time",
  breakDurationLabel: "Break Duration",
  weekOffOverrideLabel: "Week Off Override",
  isRecurringLabel: "Recurring Assignment",
  recurringDaysLabel: "Recurring Days",
  statusLabel: "Status",
  shiftPlaceholder: "Select shift",
  staffPlaceholder: "Select staff member",
  datePlaceholder: "Select date",
  branchPlaceholder: "Select branch",
  startTimePlaceholder: "Select start time",
  endTimePlaceholder: "Select end time",
  breakDurationPlaceholder: "Enter break duration",
  weekOffOverridePlaceholder: "Select week off override days",
  recurringDaysPlaceholder: "Select recurring days",
  selectShift: "Select Shift",
  selectStaff: "Select Staff Member",
  selectBranch: "Select Branch",
  selectDate: "Select Date",
  selectRecurringDays: "Select Recurring Days",
  updatedSuccessfully: "Shift assignment updated successfully.",
  deletedSuccessfully: "Shift assignment has been deleted.",
  addFailed: "Failed to assign shift.",
  updateFailed: "Failed to update shift assignment.",
  deleteFailed: "Failed to delete shift assignment.",
  cancel: "Cancel",
  update: "Update",
  assign: "Assign",
  processing: "Processing...",
  loadingLabel: "Loading assignments...",
  shiftTitleLabel: "Shift Title",
  branchLocationLabel: "Branch / Location",
  assignmentDateLabel: "Assignment Date",
  endDateLabel: "End Date",
  forRecurringLabel: "for recurring",
  selectStaffLabel: "Select Staff Members",
  selectStaffLabelText: "Choose one or multiple staff members to assign to this shift",
  recurringAssignmentLabel: "Recurring Assignment",
  checkThisToCreateRepeatingAssignmentsLabel: "Check this to create repeating assignments (e.g., every Monday-Friday)",
  selectRecurringDaysLabel: "Select Recurring Days",
  reassignStaffLabel: "Reassign Staff",
  reassigningLabel: "Reassigning",
  selectReplacementStaffLabel: "Select Replacement Staff",
  selectAvailableStaffLabel: "Select available staff",
  noAvailableStaffLabel: "No available staff for this date and branch",
  Holiday: "Holiday",
  Present: "Present",
  Absent: "Absent",
  HalfDay: "Half Day",
  Leave: "On Leave",
  Late: "Late",
  Shift: "Shift",
  AssignShift: "Assign Shift",
  ShiftCalendar: "Shift Calendar",
  ShiftCalendarDescription: "Manage and view staff shifts across all stores",
  Refresh: "Refresh",
  ClearFilters: "Clear Filters",
  Assign: "Assign",
  TotalStaff: "Total Staff",
  PresentStaff: "Present Staff",
  AbsentStaff: "Absent Staff",
  Employee: "Employee",
  ShiftTitle: "Shift Title",
  AssignmentDate: "Assignment Date",
  EndDate: "End Date",
  forRecurring: "for recurring",
  DaysOff: "Days Off",
  CheckDaysOffUncheckWorkingDays: "Check days off, uncheck working days.",
};

export const attendanceManagementStrings = {
  title: "Attendance Management",
  description: "Manage staff attendance, clock-in/out times, and leave records",
  tableTitle: "Attendance Records",
  totalRecords: "Total Records",
  presentToday: "Present Today",
  absentToday: "Absent Today",
  onLeaveToday: "On Leave Today",
  halfDayToday: "Half Day Today",
  staffLabel: "Staff Member",
  dateLabel: "Date",
  clockInLabel: "Clock In Time",
  clockOutLabel: "Clock Out Time",
  totalHoursLabel: "Total Hours",
  statusLabel: "Status",
  leaveTypeLabel: "Leave Type",
  notesLabel: "Notes",
  staffPlaceholder: "Select staff member",
  datePlaceholder: "Select date",
  clockInPlaceholder: "Select clock in time",
  clockOutPlaceholder: "Select clock out time",
  totalHoursPlaceholder: "Enter total hours",
  leaveTypePlaceholder: "Select leave type",
  notesPlaceholder: "Enter notes",
  selectStaff: "Select Staff Member",
  selectDate: "Select Date",
  selectLeaveType: "Select Leave Type",
  updatedSuccessfully: "Attendance record updated successfully.",
  deletedSuccessfully: "Attendance record has been deleted.",
  addFailed: "Failed to add attendance record.",
  updateFailed: "Failed to update attendance record.",
  deleteFailed: "Failed to delete attendance record.",
  cancel: "Cancel",
  update: "Update",
  add: "Save",
  processing: "Processing...",
  addAttendanceLabel: "Add Attendance",
  addLeaveLabel: "Add Leave",
  holidayLabel: "Holiday",
  presentLabel: "Present",
  halfDayLabel: "Half Day",
  lateLabel: "Late",
  absentLabel: "Absent",
  onLeaveLabel: "On Leave",
  loadingLabel: "Loading attendance...",
  loadingAttendanceData: "Loading attendance data...",
  noStaffFound: "No staff found",
  tryAdjustingSearchOrFilters: "Try adjusting your search or filters",
  staff: "Staff",
  notes: "Notes",
  shiftLabel: "Shift",
};

export const leaveTypeStrings = {
  title: "Leave Type Management",
  description: "Define and manage different types of leave",
  addButton: "Add Leave Type",
  addModalTitle: "Add New Leave Type",
  editModalTitle: "Edit Leave Type",
  tableTitle: "Leave Types",
  totalLeaveTypes: "Total Leave Types",
  activeLeaveTypes: "Active Leave Types",
  inactiveLeaveTypes: "Inactive Leave Types",
  recentLeaveTypes: "Recent Leave Types (7 days)",
  nameLabel: "Leave Type Name",
  isPaidLabel: "Paid Leave",
  descriptionLabel: "Description",
  statusLabel: "Status ",
  namePlaceholder: "Enter leave type name",
  descriptionPlaceholder: "Enter leave type description",
  selectStatus: "Select Status",
  updatedSuccessfully: "Leave type updated successfully.",
  deletedSuccessfully: "Leave type has been deleted.",
  addFailed: "Failed to add leave type.",
  updateFailed: "Failed to update leave type.",
  deleteFailed: "Failed to delete leave type.",
  cancel: "Cancel",
  update: "Update",
  add: "Add",
  processing: "Processing...",
};

export const leaveRequestStrings = {
  title: "Leave Management",
  description: "Manage and approve leave requests from your staff",
  addButton: "Assign Leave",
  addModalTitle: "Assign Leave",
  editModalTitle: "Edit Leave Request",
  tableTitle: "Leave Requests",
  totalRequests: "Total Requests",
  pendingRequests: "Pending Requests",
  approvedRequests: "Approved Requests",
  rejectedRequests: "Rejected Requests",
  staffLabel: "Employee ",
  storeLabel: "Store",
  leaveTypeLabel: "Leave Type ",
  startDateLabel: "Start Date ",
  endDateLabel: "End Date ",
  isHalfDayLabel: "Half Day",
  isPaidLabel: "Paid Leave",
  reasonLabel: "Reason ",
  statusLabel: "Status ",
  approvedByLabel: "Approved By",
  approvedAtLabel: "Approved At",
  staffPlaceholder: "Select Employee",
  storePlaceholder: "Select Store",
  leaveTypePlaceholder: "Select Leave Type",
  startDatePlaceholder: "dd-mm-yyyy",
  endDatePlaceholder: "dd-mm-yyyy",
  reasonPlaceholder: "Reason for leave",
  selectEmployee: "Select Employee",
  selectStore: "Select Store",
  selectLeaveType: "Select Leave Type",
  updatedSuccessfully: "Leave request updated successfully.",
  deletedSuccessfully: "Leave request has been deleted.",
  addFailed: "Failed to assign leave.",
  updateFailed: "Failed to update leave request.",
  deleteFailed: "Failed to delete leave request.",
  approveSuccess: "Leave request approved successfully!",
  rejectSuccess: "Leave request rejected successfully!",
  approveFailed: "Failed to approve leave request",
  rejectFailed: "Failed to reject leave request",
  cancel: "Cancel",
  update: "Update",
  assign: "Assign Leave",
  approve: "Approve",
  reject: "Reject",
  close: "Close",
  processing: "Processing...",
};

export const holidayStrings = {
  title: "Holiday Management",
  description: "Manage company holidays and special days",
  addButton: "Add Holiday",
  addModalTitle: "Add New Holiday",
  editModalTitle: "Edit Holiday",
  tableTitle: "Holidays",
  totalHolidays: "Total Holidays",
  activeHolidays: "Active Holidays",
  inactiveHolidays: "Inactive Holidays",
  recentHolidays: "Recent Holidays (7 days)",
  nameLabel: "Holiday Name ",
  dateLabel: "Date ",
  descriptionLabel: "Description",
  isRecurringLabel: "Recurring Holiday",
  statusLabel: "Status ",
  namePlaceholder: "Enter holiday name",
  datePlaceholder: "Select date",
  descriptionPlaceholder: "Enter holiday description",
  selectDate: "Select Date",
  updatedSuccessfully: "Holiday updated successfully.",
  deletedSuccessfully: "Holiday has been deleted.",
  addFailed: "Failed to add holiday.",
  updateFailed: "Failed to update holiday.",
  deleteFailed: "Failed to delete holiday.",
  cancel: "Cancel",
  update: "Update",
  add: "Add",
  processing: "Processing...",
};

export const payrollStrings = {
  title: "Payroll Management",
  description: "Manage staff payroll and salary calculations",
  tableTitle: "Payroll Records",
  totalRecords: "Total Records",
  pendingRecords: "Pending Records",
  paidRecords: "Paid Records",
  staffLabel: "Staff Member ",
  monthLabel: "Month ",
  yearLabel: "Year ",
  basicSalaryLabel: "Salary ",
  daysWorkedLabel: "Days Worked ",
  totalDaysLabel: "Total Days ",
  paidLeavesLabel: "Paid Leaves ",
  unpaidLeavesLabel: "Unpaid Leaves ",
  deductionsLabel: "Deductions ",
  netSalaryLabel: "Net Salary ",
  statusLabel: "Status ",
  paidAtLabel: "Paid At",
  staffPlaceholder: "Select staff member",
  monthPlaceholder: "Select month",
  yearPlaceholder: "Select year",
  basicSalaryPlaceholder: "Enter salary",
  daysWorkedPlaceholder: "Enter days worked",
  totalDaysPlaceholder: "Enter total days",
  paidLeavesPlaceholder: "Enter paid leaves",
  unpaidLeavesPlaceholder: "Enter unpaid leaves",
  deductionsPlaceholder: "Enter deductions",
  netSalaryPlaceholder: "Enter net salary",
  selectStaff: "Select Staff Member",
  selectMonth: "Select Month",
  selectYear: "Select Year",
  updatedSuccessfully: "Payroll record updated successfully.",
  deletedSuccessfully: "Payroll record has been deleted.",
  noPayrollRecordsFound: "No payroll records found",
  addFailed: "Failed to add payroll record.",
  updateFailed: "Failed to update payroll record.",
  deleteFailed: "Failed to delete payroll record.",
  cancel: "Cancel",
  update: "Update",
  add: "Add",
  processing: "Processing...",
};

// Expense Management
export const expenseManagement = "Expense Management";
export const expenseCategoryManagement = "Expense Category Management";
export const addExpense = "Add Expense";
export const addExpenseCategory = "Add Expense Category";
export const expenseCategory = "Expense Category";
export const expenseCategories = "Expense Categories";
export const categoryName = "Category Name";
export const categoryDescription = "Description";
export const categoryStatus = "Status";
export const active = "Active";
export const inactive = "Inactive";
export const expenseAmount = "Amount";
export const expenseDescription = "Description";
export const expenseDate = "Expense Date";
export const paymentMethod = "Payment Method";
export const reference = "Reference";
export const notes = "Notes";
export const attachments = "Attachments";
export const totalExpenses = "Total Expenses";
export const pendingExpenses = "Pending Expenses";
export const approvedExpenses = "Approved Expenses";
export const rejectedExpenses = "Rejected Expenses";
export const monthlyExpenses = "Monthly Expenses";
export const expenseStats = "Expense Statistics";
export const recentExpenses = "Recent Expenses";
export const expenseBreakdown = "Expense Breakdown";
export const cash = "Cash";
export const bankTransfer = "Bank Transfer";
export const creditCard = "Credit Card";
export const check = "Check";
export const other = "Other";
export const pending = "Pending";
export const approved = "Approved";
export const rejected = "Rejected";

// Tax Management
export const taxManagement = "Tax Management";
export const addTax = "Add Tax";
export const taxName = "Tax Name";
export const taxType = "Tax Type";
export const valueType = "Value Type";
export const value = "Value";
export const inclusive = "Inclusive";
export const exclusive = "Exclusive";
export const taxDescription = "Description";
export const totalTaxes = "Total Taxes";
export const activeTaxes = "Active Taxes";
export const inactiveTaxes = "Inactive Taxes";
export const inclusiveTaxes = "Inclusive Taxes";
export const exclusiveTaxes = "Exclusive Taxes";
export const fixedTaxes = "Fixed Taxes";
export const percentageTaxes = "Percentage Taxes";
export const taxStats = "Tax Statistics";
export const recentTaxes = "Recent Taxes";
export const taxBreakdown = "Tax Breakdown";
export const editTax = "Edit Tax";
export const deleteTax = "Delete Tax";
export const newTax = "New Tax";
export const taxDetails = "Tax Details";
export const taxCalculation = "Tax Calculation";
export const baseAmount = "Base Amount";
export const taxAmount = "Tax Amount";
export const totalAmount = "Total Amount";

// Financial Metrics
export const totalRevenue = "Total Revenue";
export const netProfit = "Net Profit";
export const profitMargin = "Profit Margin";
export const expenseRatio = "Expense Ratio";
export const monthlyRevenue = "Monthly Revenue";
export const monthlyProfit = "Monthly Profit";
export const financialMetrics = "Financial Metrics";
export const profitLoss = "Profit & Loss";
export const revenue = "Revenue";
export const expenses = "Expenses";
export const profit = "Profit";
export const loss = "Loss";
export const margin = "Margin";
export const ratio = "Ratio";
export const approveExpense = "Approve Expense";
export const rejectExpense = "Reject Expense";
export const expenseApproval = "Expense Approval";
export const approvalNotes = "Approval Notes";
export const approvedBy = "Approved By";
export const approvedAt = "Approved At";
export const financialImpact = "Financial Impact";

// Coupon Management
export const couponManagement = "Coupon Management";
export const couponManagementDescription = "Advanced coupon management with full administrative control";
export const additionalInformationLabel = "Additional Information";
export const limitLabel = "Limit";
export const addCoupon = "Add Coupon";
export const updateCoupon = "Update Coupon";
export const couponCode = "Coupon Code";
export const shortDescription = "Short Description";
export const couponType = "Type";
export const usedCountLabel = "Used Count";
export const discountAmount = "Discount Amount";
export const limit = "Limit";
export const selectPlan = "Select Plan";
export const couponStatus = "Status";
export const totalCoupons = "Total Coupons";
export const activeCoupons = "Active Coupons";
export const inactiveCoupons = "Inactive Coupons";
export const percentageCoupons = "Percentage Coupons";
export const fixedCoupons = "Fixed Coupons";
export const totalUsage = "Total Usage";
export const totalSavings = "Total Savings";
export const expiringSoon = "Expiring Soon";
export const couponStats = "Coupon Statistics";
export const recentCoupons = "Recent Coupons";
export const couponUsage = "Coupon Usage";
export const editCoupon = "Edit Coupon";
export const deleteCoupon = "Delete Coupon";
export const newCoupon = "New Coupon";
export const couponDetails = "Coupon Details";
export const usageHistory = "Usage History";
export const usedCount = "Used Count";
export const remainingUses = "Remaining Uses";
export const validFrom = "Valid From";
export const validUntil = "Valid Until";
export const discountType = "Discount Type";
export const usageLimit = "Usage Limit";
export const applicablePlans = "Applicable Plans";
export const couponValidation = "Coupon Validation";
export const generateCode = "Generate Coupon";
export const copyCode = "Copy Code";
export const duplicateCoupon = "Duplicate Coupon";
export const bulkActions = "Bulk Actions";
export const selectAll = "Select All";
export const deselectAll = "Deselect All";
export const activateSelected = "Activate Selected";
export const deactivateSelected = "Deactivate Selected";
export const deleteSelected = "Delete Selected";

//Coupon History Management
export const percentageMustBeBetween1And100 = "Percentage must be between 1 and 100";
export const completeCouponInformation = "Complete coupon information";
export const basicInformationLabel = "Basic Information";
export const couponCodeLabel = "Coupon Code";
export const typeLabel = "Type";
export const discountAmountLabel = "Discount Amount";

//Shift Creation
export const addShift = "Add";
export const editShift = "Edit";
export const deleteShift = "Delete";
export const shiftCreation = "Shift Type";
export const shiftTitle = "Shift Title";
export const shiftStartTime = "Shift Start Time";
export const shiftEndTime = "Shift End Time";
export const shiftSave = "Save";
export const shiftType = "Shift Type";
export const shiftBreakDuration = "Shift Break Duration";

//shift calendar
export const shiftCalendar = "Shift Calendar";
export const shiftCalendarDescription = "View and manage shifts for your staff";
export const shiftCalendarAddButton = "Add";
export const shiftCalendarEditButton = "Edit";
export const shiftCalendarDeleteButton = "Delete";
export const shiftCalendarTitle = "Shift Calendar";
export const shiftCalendarStartTime = "Shift Start Time";
export const shiftCalendarEndTime = "Shift End Time";
export const shiftCalendarBreakDuration = "Shift Break Duration";
export const shiftWeekly = "Weekly";
export const shiftMonthly = "Monthly";

//Attendance

export const updateAttendance = "Update Attendance";
export const addAttendance = "Add Attendance";
export const addLeave = "Add Leave";
export const editAttendance = "Edit Attendance";
export const editLeave = "Edit Leave";
export const deleteAttendance = "Delete Attendance";
export const deleteLeave = "Delete Leave";
export const saveAttendance = "Save";
export const attendanceManagement = "Attendance Management";

// Attendance Status Constants
export const ATTENDANCE_STATUS = {
  PRESENT: "Present",
  ABSENT: "Absent",
  ON_LEAVE: "On Leave",
  HALF_DAY: "Half Day",
  HOLIDAY: "Holiday",
  DAY_OFF: "Day Off",
  LATE: "Late"
} as const;

//Store Management
export const storeManagement = "Store Management";
export const addStore = "Add Store";
export const saveStore = "Save";
export const editStore = "Edit";
export const configureStoreDetails = "Configure store details";
export const manageStoreLocationsAndInformation = "Manage your store locations and information";

// Purchase Management
export const Order = "Order";
export const Return = "Return";

export const suppliers = "Suppliers";
export const purchaseManagement = "Purchase Management";
export const purchaseManagemntTitle = "Manage purchase orders, returns, and supplier relationships";
export const purchaseOrderManagement = "Purchase Order Management";
export const purchaseReturnManagement = "Purchase Return Management";
export const purchaseOrder = "Purchase Order";
export const purchaseOrderTitle = "Create and manage purchase orders with suppliers";
export const purchaseReturn = "Purchase Return";
export const purchaseReturnTitle = "Process returns and update inventory accordingly";
export const suppliersTitle = "Manage supplier information and relationships";
export const recentPurchaseOrders = "Recent Purchase Orders";
export const recentReturns = "Recent Returns";
export const purchaseOrderStatus = "Purchase Order Status";
export const purchaseReturnStatus = "Purchase Return Status";
export const purchaseOrderDate = "Purchase Order Date";
export const purchaseReturnDate = "Purchase Return Date";
export const purchaseOrderAmount = "Purchase Order Amount";
export const purchaseReturnAmount = "Purchase Return Amount";
export const purchaseOrderNumber = "Purchase Order Number";
export const purchaseReturnNumber = "Purchase Return Number";
export const purchaseOrderSupplier = "Purchase Order Supplier";
export const purchaseReturnSupplier = "Purchase Return Supplier";
export const purchaseOrderSupplierName = "Purchase Order Supplier Name";
export const purchaseReturnSupplierName = "Purchase Return Supplier Name";
export const purchaseOrderSupplierEmail = "Purchase Order Supplier Email";
export const purchaseReturnSupplierEmail = "Purchase Return Supplier Email";
export const purchaseOrderSupplierPhone = "Purchase Order Supplier Phone";
export const purchaseReturnSupplierPhone = "Purchase Return Supplier Phone";
export const purchaseOrderSupplierAddress = "Purchase Order Supplier Address";
export const purchaseReturnSupplierAddress = "Purchase Return Supplier Address";
export const purchaseOrderSupplierCity = "Purchase Order Supplier City";
export const purchaseReturnSupplierCity = "Purchase Return Supplier City";
export const purchaseOrderSupplierState = "Purchase Order Supplier State";
export const purchaseReturnSupplierState = "Purchase Return Supplier State";
export const purchaseOrderSupplierCountry = "Purchase Order Supplier Country";
export const purchaseReturnSupplierCountry = "Purchase Return Supplier Country";
export const purchaseOrderSupplierPostalCode = "Purchase Order Supplier Postal Code";
export const purchaseReturnSupplierPostalCode = "Purchase Return Supplier Postal Code";
export const purchaseOrderSupplierContactPerson = "Purchase Order Supplier Contact Person";
export const purchaseReturnSupplierContactPerson = "Purchase Return Supplier Contact Person";
export const purchaseOrderSupplierStatus = "Purchase Order Supplier Status";
export const purchaseReturnSupplierStatus = "Purchase Return Supplier Status";
export const purchaseOrderSupplierCreatedAt = "Purchase Order Supplier Created At";
export const purchaseReturnSupplierCreatedAt = "Purchase Return Supplier Created At";
export const purchaseOrderSupplierUpdatedAt = "Purchase Order Supplier Updated At";
export const purchaseReturnSupplierUpdatedAt = "Purchase Return Supplier Updated At";

export const totalOrders = "Total Orders";
export const totalAmounts = "Total Amounts";
export const pendingOrders = "Pending Orders";
export const totalReturns = "Total Returns";
export const viewAllReturns = "View All Returns";
export const viewAllOrders = "View All Orders";

// Loyalty Points Management
export const loyaltyPointsHeading = "Loyalty Points Config";
export const loyaltyPointsBio = "Manage loyalty points configuration and history";
export const addLoyaltyConfig = "Add";
export const loyaltyConfigTitle = "Loyalty Points Configuration";
export const loyaltyHistoryTitle = "Loyalty Points History";
export const minimumAmountLabel = "Minimum Amount ";
export const loyaltyPointsLabel = "Loyalty Points ";
export const redeemTypeLabel = "Redeem Type ";
export const redemptionThresholdLabel = "Redemption Threshold ";
export const maxAmountReceivedLabel = "Max Amount Received ";
export const selectRedeemType = "Select Redeem Type";
export const fullRedeemType = "Full";
export const partialRedeemType = "Partial";
export const activeStatus = "Active";
export const inactiveStatus = "Inactive";
export const minimumAmountPlaceholder = "Enter minimum amount";
export const loyaltyPointsPlaceholder = "Enter loyalty points";
export const redemptionThresholdPlaceholder = "Enter redemption threshold";
export const maxAmountReceivedPlaceholder = "Enter max amount received";
export const configSavedSuccessfully = "Loyalty configuration saved successfully.";
export const configUpdateFailed = "Failed to update loyalty configuration.";
export const configAddFailed = "Failed to add loyalty configuration.";
export const saveLoyaltyConfig = "Save";

// Loyalty Points History
export const transactionIdLabel = "Transaction ID / Reference No";
export const loyaltyPointsHistoryBio = "View and manage loyalty points transaction history";
export const customerNameLabel = "Customer Name / ID";
export const orderIdLabel = "Order ID";
export const earnedPointsLabel = "Earned Points";
export const redeemedPointsLabel = "Redeemed Points";
export const balancePointsLabel = "Balance Points";
export const transactionTypeLabel = "Transaction Type";
export const dateTimeLabel = "Date & Time";
export const handledByLabel = "Handled By (User/Admin)";
export const remarksLabel = "Remarks / Notes";
export const earnTransactionType = "Earn";
export const redeemTransactionType = "Redeem";
export const allTransactionTypes = "All Types";
export const loyaltyHistoryEarned = "Earned";
export const loyaltyHistoryRedeemed = "Redeemed";
export const searchPlaceholder = "Search by customer, order ID, or transaction ID...";
export const exportButton = "Export";

// Gift Card Management
export const giftCardHeading = "Gift Card Config";
export const giftCardBio = "Manage gift card configuration and history";
export const addGiftCard = "Add";
export const giftCardConfigTitle = "Gift Card Configuration";
export const giftCardHistoryTitle = "Gift Card History";
export const giftCardNameLabel = "Gift Card Name ";
export const giftCardNumberLabel = "Gift Card Number ";
export const giftCardValueLabel = "Gift Card Value ";
export const thresholdAmountLabel = "Threshold Amount ";
export const validityLabel = "Validity ";
export const customersLabel = "Customers ";
export const termsAndConditionsLabel = "Terms & Conditions";
export const giftCardNamePlaceholder = "Enter gift card name";
export const giftCardNumberPlaceholder = "Enter gift card number";
export const giftCardValuePlaceholder = "Enter gift card value";
export const thresholdAmountPlaceholder = "Enter threshold amount (optional)";
export const validityPlaceholder = "Select validity date";
export const selectCustomerScope = "Select Customer Scope";
export const allCustomers = "All";
export const specificCustomers = "Specific";
export const autoNumberGeneration = "Auto";
export const manualNumberGeneration = "Manual";
export const giftCardSavedSuccessfully = "Gift card saved successfully.";
export const giftCardUpdateFailed = "Failed to update gift card.";
export const giftCardAddFailed = "Failed to add gift card.";
export const saveGiftCard = "Save";

// Gift Card History
export const giftCardIdLabel = "Gift Card ID / Reference No";
export const giftCardNumberHistoryLabel = "Gift Card Number";
export const assignedCustomerLabel = "Assigned Customer";
export const issuedDateLabel = "Issued Date";
export const expiryDateLabel = "Expiry Date";
export const giftCardValueHistoryLabel = "Gift Card Value";
export const usedAmountLabel = "Used Amount";
export const remainingBalanceLabel = "Remaining Balance";
export const redemptionDatesLabel = "Redemption Date(s)";
export const sentViaLabel = "Sent Via";
export const giftCardHistoryStatusLabel = "Status";
export const handledByGiftCardLabel = "Handled By";
export const remarksGiftCardLabel = "Remarks / Notes";
export const activeGiftCardStatus = "Active";
export const usedGiftCardStatus = "Used";
export const expiredGiftCardStatus = "Expired";
export const allGiftCardStatuses = "All Statuses";
export const emailSendVia = "Email";
export const whatsappSendVia = "WhatsApp";
export const giftCardSearchPlaceholder = "Search by gift card number, customer, or reference ID...";


//Purchase Return Management
export const productDetails = "Product Details";
export const selectPurchaseOrder = "Select Purchase Order";
export const selectStore = "Select Store";
export const noStoresAvailable = "No stores available";
export const statusLabel = "Status";
export const returnDateLabel = "Return Date";
export const orderDetailsLabel = "Order Details";
export const orderNumberLabel = "Order Number";
export const storeLabel = "Store";
export const storeProfileLabel = "Store Profile";
export const descriptionLabel = "Description";
export const locationLabel = "Location";
export const coordinatesLabel = "Coordinates";
export const latLabel = "Lat";
export const longLabel = "Long";
export const completeStoreInformationAndDetailsLabel = "Complete store information and details";
export const storeInformationLabel = "Store Information";
export const storeNameLabel = "Store Name";
export const pocLabel = "POC";
export const latitudeLabel = "Latitude";
export const longitudeLabel = "Longitude";
export const purchaseOrderLabel = "Purchase Order";
export const supplierLabel = "Supplier";
export const purchaseDateLabel = "Purchase Date";
export const totalAmountLabel = "Total Amount";
export const productDetailsLabel = "Product Details";
export const productNameLabel = "Product Name";
export const returnQuantityLabel = "Return Quantity";
export const unitPriceLabel = "Unit Price";
export const taxRateLabel = "Tax Rate %";
export const actionsLabel = "Actions";
export const totalLabel = "Total";
export const amountLabel = "Amount";
export const taxLabel = "Tax";
export const grandTotalLabel = "Grand Total";
export const returnReasonNotesLabel = "Return Reason/Notes";
export const characters = "characters";
export const cancelLabel = "Cancel";
export const saveLabel = "Save";
export const purchaseReturnDetailsLabel = "Purchase Return Details";
export const completeReturnInformationAndHistoryLabel = "Complete return information and history";
export const returnInformationLabel = "Return Information";
export const returnNumberLabel = "Return Number";
export const financialInformationLabel = "Financial Information";
export const totalRefundAmountLabel = "Total Refund Amount";
export const createdByLabel = "Created By";
export const processedByLabel = "Processed By";
export const processedAtLabel = "Processed At";
export const returnedProductsLabel = "Returned Products";
export const productLabel = "Product";
export const skuLabel = "SKU";
export const variantLabel = "Variant";
export const quantityLabel = "Quantity";
export const subtotalLabel = "Subtotal";
export const refundAmountLabel = "Refund Amount";
export const reasonLabel = "Reason";
export const purchaseReturnHistoryLabel = "Purchase Return History";
export const completeHistoryOfAllPurchaseReturnsLabel = "Complete history of all purchase returns";
export const noHistoryFoundLabel = "No History Found";



export const ordersLabel = "Orders";
export const historyLabel = "History";
export const noPurchaseOrdersYetLabel = "No Purchase Orders Yet";
export const getStartedByCreatingYourFirstPurchaseOrderLabel = "Get started by creating your first purchase order. You can manage suppliers, track orders, and monitor deliveries all in one place.";
export const createYourFirstPurchaseOrderLabel = "Create Your First Purchase Order";
export const purchaseOrderHistoryLabel = "Purchase Order History";
export const completeHistoryOfAllPurchaseOrdersLabel = "Complete history of all purchase orders";
export const balanceDueLabel = "Due Amount";
export const supplierInformationLabel = "Supplier Information";
export const detailsLabel = "Details";
export const emailLabel = "Email";
export const phoneLabel = "Phone";
export const addressLabel = "Address";
export const shippingDetailsLabel = "Shipping Details";
export const deliveryDetailsLabel = "Delivery Details";

export const countryLabel = "Country";
export const stateLabel = "State";
export const cityLabel = "City";
export const postalCodeLabel = "Postal Code";

export const purchaseOrderNumberLabel = "Purchase Order Number";
export const expectedDeliveryDateLabel = "Expected Delivery Date";
export const purchaseTermsLabel = "Purchase Terms";
export const selectTermsLabel = "Select Terms";
export const notesLabel = "Notes";
export const charactersLabel = "characters";
export const discountPercentageLabel = "Discount %";
export const taxAmountLabel = "Tax Amount";
export const cancelButtonLabel = "Cancel";
export const submittingLabel = "Submitting...";
export const submitOrderLabel = "Submit Order";
export const purchaseOrderDetailsLabel = "Purchase Order Details";
export const completePurchaseOrderInformationAndDetailsLabel = "Complete purchase order information and details";
export const receiveLabel = "Receive";
export const changeStatusLabel = "Change Status";
export const convertToBillLabel = "Convert to Bill";
export const receiveStatusLabel = "Receive Status";
export const billStatusLabel = "Bill Status";
export const showPDFViewLabel = "Show PDF View";
export const whatsNextLabel = "WHAT'S NEXT?";
export const convertItToABillOrCreateAReceiveToCompleteYourPurchaseLabel = "Convert it to a bill or create a receive to complete your purchase.";
export const purchaseOrderTitleLabel = "PURCHASE ORDER";
export const dateLabel = "Date";
export const supplierAddressLabel = "Supplier Address";
export const deliverToLabel = "Deliver To";
export const itemDescriptionLabel = "Item & Description";
export const rateLabel = "Rate";
export const subTotalLabel = "Sub Total";
export const authorizedSignatureLabel = "Authorized Signature";
export const pdfTemplateLabel = "PDF Template";
export const pdfTemplateLabelValue = "Standard Template";
export const changeLabel = "Change";

export const orderInformationLabel = "Order Information";
export const supplierEmailLabel = "Supplier Email";
export const expectedDeliveryLabel = "Expected Delivery";
export const paymentTermsLabel = "Payment Terms";
export const discountTypeLabel = "Discount Type";
export const billingAddressLabel = "Billing Address";
export const contactPersonLabel = "Contact Person";
export const shippingAddressLabel = "Shipping Address";

export const activityTimelineLabel = "Activity Timeline";
export const createdOnLabel = "Created On";
export const updatedOnLabel = "Updated On";
export const lastModifiedLabel = "Last Modified";
export const lineTotalLabel = "Line Total";
export const receivedLabel = "Received";
export const partialLabel = "Partial";
export const pendingLabel = "Pending";

export const noItemsFoundInThisPurchaseOrderLabel = "No items found in this purchase order.";

// Notification Templates
export const notificationTemplateStrings = {
  templateType: "Template Type",
  to: "To",
  userType: "User Type",
  dynamicParameters: "Dynamic Parameters",
  emailTemplate: "Email Template",
  subject: "Subject",
  enterEmailSubject: "Enter email subject",
  recipientOptions: {
    admin: "Admin",
    customer: "Customer",
    user: "User",
    supplier: "Supplier",
    manager: "Manager"
  },
  parameters: [
    'Customer Name', 'Customer Email', 'User Name', 'User Email', 'Admin Name', 'Admin Email',
    'Order ID', 'Amount Paid', 'Payment Date', 'Coupon Code', 'Coupon Type', 'Coupon Discount',
    'Reset Link', 'Current Date', 'Company Name', 'Coupon Description',
    'Sender Name', 'Gift Card Code', 'Gift Card Image', 'Gift Card Amount', 'Gift Card Terms & Conditions', 'Expiry Date', 'Personal Message',
    'Store Name', 'Support Email', 'Store Website', 'Purchase Order Number', 'Purchase Date', 'Purchase Order Status', 'Supplier Name', 'Supplier Email', 'Total Amount', 'Recipient Name', 'Product Name', 'Product SKU', 'Current Stock', 'Minimum Stock', 'Store Manager',
  ],
  selectRecipients: "Select recipients",
  requiredField: "This field is required"
};
export const receiveItemsLabel = "Receive Items";
export const poNumberLabel = "PO Number";
export const selectStoreLabel = "Select Store";
export const noStoresAvailableLabel = "No stores available";
export const receivedByLabel = "Received By";
export const itemsLabel = "Items";
export const orderedLabel = "Ordered";
export const quantityToReceiveLabel = "Quantity to Receive";
export const processingLabel = "Processing...";
export const noRecentReturnLabel = "No recent returns"

export const supplierNameLabel = "Supplier Name";
export const codeLabel = "Code";
export const readOnlyLabel = "Read-only";
export const genderLabel = "Gender";
export const pincodeLabel = "Pincode";
export const customerProfileLabel = "Customer Profile";
export const completeCustomerInformationAndDetailsLabel = "Complete customer information and details";
export const customerInformationLabel = "Customer Information";
export const CustomerNameLabel = "Customer Name";
export const customerCodeLabel = "Customer Code";
export const autoGeneratedLabel = "Auto-generated, editable";
export const imageLabel = "Supplier Profile";
export const completeSupplierInformationLabel = "Complete supplier information and details";
export const suppplierNameLabel = "Supplier Name";
export const emailAddressLabel = "Email Address";
export const contactNumberLabel = "Contact Number";
export const addressInfoLabel = "Address Information";
export const supplierCodeLabel = "Supplier Code";

export const loadingStoresLabel = "Loading stores...";
export const staffLabel = "Staff";
export const categoryLabel = "Category";
export const expenseInformationLabel = "Expense Information";
export const expenseDetailsLabel = "Expense Details";
export const completeExpenseInformationAndDetailsLabel = "Complete expense information and details";
export const paymentInformationLabel = "Payment Information";

export const categoryProfileLabel = "Category Profile";
export const completeCategoryInformationAndDetailsLabel = "Complete category information and details";
export const categoryInformationLabel = "Category Information";
export const categoryNameLabel = "Category Name";
export const statusInformationLabel = "Status Information";
export const currentStatusLabel = "Current Status";
export const addCategoryLabel = "Add Category";
export const editCategoryLabel = "Edit Category";
export const configureExpenseCategoryDetailsAndInformationLabel = "Configure expense category details and information";
export const manageExpenseCategoriesForOrganizingExpensesLabel = "Manage expense categories for organizing expenses";


//Inventory Management
export const brandImageLabel = "Brand Image";
export const addImageLabel = "Add Image";
export const jpegPngUpTo2MbLabel = "JPEG, PNG up to 2 MB";
export const brandNameLabel = "Brand Name";
export const brandProfileLabel = "Brand Profile";
export const completeBrandInformationAndDetailsLabel = "Complete brand information and details";
export const brandInformationLabel = "Brand Information";
export const imageBrandLabel = "Image";

export const expiredStockManagementLabel = "Expired Stock Management";
export const viewAndManageExpiredStockItemsLabel = "View and manage expired stock items";

export const lowStockManagementLabel = "Low Stock Management";
export const viewAndManageLowStockItemsLabel = "View and manage low stock items";

export const durationLabel = "Duration"


//People Management
export const peopleManagementLabel = "People Management";
export const viewAndManagePeopleLabel = "View and manage people";
export const configureCustomerDetailsAndInformation = "Configure customer details and information";
export const manageCustomerInformationAndRelationships = "Manage customer information and relationships";
export const addCustomer = "Add Customer";
export const editCustomer = "Edit Customer";

export const roleAndAddressInformationLabel = "Role & Address Information";
export const roleLabel = "Role";

export const rowsPerPageLabel = "Rows per page";
export const allStoresLabel = "All Stores";
export const generateLabel = "Generate";
export const assignLabel = "Assign";

export const holidayManagementStrings = {
  title: "Holiday Management",
  description: "Manage holidays and special days for your organization",
  tableTitle: "Holiday Records",
  totalRecords: "Total Records",
  presentToday: "Present Today",
  absentToday: "Absent Today",
  onLeaveToday: "On Leave Today",
  halfDayToday: "Half Day Today",
  staffLabel: "Staff Member",
  dateLabel: "Date",
  addHolidayLabel: "Add Holiday",
  editHolidayLabel: "Edit Holiday",
  loadingLabel: "Loading holidays...",
  noHolidaysLabel: "No holidays",
  todayLabel: "Today",
  holidayNameLabel: "Holiday Name",
  recurringHolidayLabel: "Recurring Holiday",
  repeatsEveryYearLabel: "repeats every year",
};

export const hrmDashboardStrings = {
  title: "HRM Dashboard",
  description: "Manage your human resources efficiently",
  totalStaffLabel: "Total Staff",
  totalLeavesLabel: "Total Leaves",
  totalHolidaysLabel: "Total Holidays",
  totalPayrollLabel: "Total Payroll",
  totalManagersLabel: "Total Managers",
  activeShiftsLabel: "Active Shifts",
  pendingLeavesLabel: "Pending Leaves",
  quickActionsLabel: "Quick Actions",
  recentStaffLabel: "Recent Staff",
  viewAllStaffLabel: "View All Staff",
  recentLeaveRequestsLabel: "Recent Leave Requests",
  viewAllLeavesLabel: "View All Leaves",
};

export const leaveManagementStrings = {
  title: "Leave Management",
  description: "Manage and approve leave requests from your staff",
  addButton: "Assign Leave",
  addModalTitle: "Assign Leave",
  editModalTitle: "Edit Leave Request",
  tableTitle: "Leave Requests",
  totalRequests: "Total Requests",
  pendingRequests: "Pending Requests",
  approvedRequests: "Approved Requests",
  rejectedRequests: "Rejected Requests",
  loadingLabel: "Loading leave requests...",
  leaveRequestDetailsLabel: "Leave Request Details",
  employeeLabel: "Employee",
  storeLabel: "Store",
  leaveTypeLabel: "Leave Type",
  statusLabel: "Status",
  paidLeaveLabel: "Paid Leave",
  dateDurationLabel: "Date & Duration",
  startDateLabel: "Start Date",
  endDateLabel: "End Date",
  durationLabel: "Duration",
  approvedByLabel: "Approved By",
  approvedAtLabel: "Approved At",
  reasonLabel: "Reason",
  selectLeaveTypeLabel: "Select Leave Type",
  selectDurationLabel: "Select Duration",
  fullDayLabel: "Full Day",
  halfDayLabel: "Half Day",
  multipleLabel: "Multiple",
  dismissLabel: "Dismiss",
};


export const leaveTypeManagementStrings = {
  title: "Leave Type Management",
  description: "Manage and approve leave requests from your staff",
  addButton: "Add Leave Type",
  addModalTitle: "Add New Leave Type",
  editModalTitle: "Edit Leave Type",
  tableTitle: "Leave Types",
  totalLeaveTypes: "Total Leave Types",
  activeLeaveTypes: "Active Leave Types",
  inactiveLeaveTypes: "Inactive Leave Types",
  recentLeaveTypes: "Recent Leave Types (7 days)",
  loadingLabel: "Loading leave types...",
  nameLabel: "Name",
  typeLabel: "Type",
  paidLabel: "Paid",
  unpaidLabel: "Unpaid",
  leaveCountLabel: "Leave Count",
  statusLabel: "Status",
  descriptionLabel: "Description",
};


export const payrollManagementStrings = {
  title: "Payroll Management",
  employeePeriodLabel: "Employee & Period",
  description: "Manage and approve payroll from your staff",
  addButton: "Add Payroll",
  addModalTitle: "Add New Payroll",
  editModalTitle: "Edit Payroll",
  tableTitle: "Payrolls",
  totalPayrolls: "Total Payrolls",
  activePayrolls: "Active Payrolls",
  inactivePayrolls: "Inactive Payrolls",
  recentPayrolls: "Recent Payrolls (7 days)",
  employeeLabel: "Employee",
  periodLabel: "Period",
  monthLabel: "Month",
  yearLabel: "Year",
  basicSalaryLabel: "Basic Salary",
  daysWorkedLabel: "Days Worked",
  totalDaysLabel: "Total Days",
  paidLeavesLabel: "Paid Leaves",
  unpaidLeavesLabel: "Unpaid Leaves",
  deductionsLabel: "Deductions",
  netSalaryLabel: "Net Salary",
  selectMonthLabel: "Select Month",
  salarySummaryLabel: "Salary & Summary",
  salaryLabel: "Salary",
  totalDeductionsLabel: "Total Deductions",
  unpaidDaysLabel: "Unpaid Days",
  daysPresentLabel: "days present",
  basedOnLabel: "Based on",
  attendanceLeaveSummaryLabel: "Attendance & Leave Summary",
  calculatingLabel: "Calculating...",
  autoCalculatedLabel: "Auto-calculated",
  totalDaysHintLabel: "Total days in",
  unpaidLeavesHintLabel: "Unpaid leaves + absent days",
  daysMarkedAsPresentLabel: "Days marked as present",
  paidLeavesHintLabel: "Approved paid leave days",
  remarksLabel: "Remarks",
  additionalNotesLabel: "Additional Notes",
  payrollLabel: "Payroll",
};


export const salarySlipStrings = {
  title: "Salary Slip",
  description: "View and manage salary slips for your staff",
  addButton: "Add Salary Slip",
  addModalTitle: "Add New Salary Slip",
  editModalTitle: "Edit Salary Slip",
  tableTitle: "Salary Slips",
  totalSalarySlips: "Total Salary Slips",
  activeSalarySlips: "Active Salary Slips",
  inactiveSalarySlips: "Inactive Salary Slips",
  recentSalarySlips: "Recent Salary Slips (7 days)",
  posDashboard: "POS Dashboard",
  salarySlip: "SALARY SLIP",
  forTheMonthOf: "For the month of",
  employeeNameLabel: "Employee Name",
  employeeIdLabel: "Employee ID",
  designationLabel: "Designation",
  storeLabel: "Store",
  statusLabel: "Status",
  earningsLabel: "Earnings",
  salaryLabel: "Salary",
  attendanceDetailsLabel: "Attendance Details",
  daysWorkedLabel: "Days Worked",
  totalDaysLabel: "Total Days",
  paidLeavesLabel: "Paid Leaves",
  unpaidDaysLabel: "Unpaid Days",
  deductionsLabel: "Deductions",
  netSalaryLabel: "Net Salary",
  remarksLabel: "Remarks",
  downloadPdfLabel: "Download PDF",
  emailToEmployeeLabel: "Email to Employee",
  generatedOnLabelText: "This is a computer generated salary slip and does not require signature",
  generatedOnLabel: "Generated on",
};


export const shiftManagementStrings = {
  title: "Shift Management",
  description: "Manage work shifts for your staff",
  addShift: "Add Shift",
  editShift: "Edit Shift",
  loadingLabel: "Loading shifts...",
  breakDurationLabel: "Break Duration (minutes)",
  startTimeLabel: "Start Time",
  endTimeLabel: "End Time",
  weekOffLabel: "Week Off Days",
  shiftDetails: "Shift Details",
  shiftDetailsSubtitle: "Complete shift information and details",
  shiftInfo: "Shift Information",
  shiftTitle: "Shift Title",
  startTime: "Start Time",
  endTime: "End Time",
  breakDuration: "Break Duration",
};

export const staffManagementStrings = {
  title: "Staff Management",
  description: "Manage your staff members",
  addStaff: "Add Staff",
  editStaff: "Edit Staff",
  loadingLabel: "Loading staff...",
};

// Brand constants
export const brandheading = "Brand Management";
export const brandbio = "Manage your product brands";
export const brandname = "Brand Name";
export const branddetails = "Brand Details";
export const branddetailsbio = "Complete brand information and details";
export const brandinformation = "Brand Information";
export const activitytimeline = "Activity Timeline";
export const editBrand = "Edit Brand";
export const max250characters = "Maximum 250 Characters";

// Mail Settings constants
export const mailSettingStrings = {
  title: "Mail Settings",
  description: "Configure your SMTP mail settings",
  emailLabel: "Email",
  hostLabel: "SMTP Host",
  portLabel: "SMTP Port",
  encryptionLabel: "Encryption",
  passwordLabel: "SMTP Password",
  verifyingLabel: "Verifying...",
  verifyButton: "Verify Settings",
  deleteButton: "Delete Settings",
  saveButton: "Save Settings",
  savingLabel: "Saving...",
  verifiedStatus: "Verified",
  notVerifiedStatus: "Not Verified",
  lastVerifiedLabel: "Last Verified",
  verifySuccess: "Mail settings verified successfully",
  verifyError: "Failed to verify mail settings",
  saveSuccess: "Mail settings saved successfully",
  saveError: "Failed to save mail settings",
  deleteSuccess: "Mail settings deleted successfully",
  deleteError: "Failed to delete mail settings",
  tlsLabel: "TLS",
  sslLabel: "SSL",
  noneLabel: "None",
  deleteConfirm: "Are you sure you want to delete the mail settings?",
};

// Misc Settings constants
export const miscSettingStrings = {
  title: "Misc Settings",
  description: "Configure miscellaneous system settings",
  enableDarkMode: "Enable Dark Mode",
  allowUserToggleDarkMode: "Allow users to toggle dark mode",
  saveButton: "Save Settings",
  savingLabel: "Saving...",
};

// Payment Settings constants
export const paymentSettingStrings = {
  title: "Payment Method",
  description: "Configure your payment settings",
  submitButton: "Submit",
  savingLabel: "Saving...",
  razorpay: {
    title: "Razorpay",
    secretKey: "Secret Key",
    appKey: "App key",
    secretKeyError: "Must be a valid RazorPay key",
    appKeyError: "Must be a valid RazorPay Publickey",
  },
  stripe: {
    title: "Stripe",
    secretKey: "Secret Key",
    appKey: "App key",
  },
  paystack: {
    title: "Paystack",
    secretKey: "Secret Key",
    appKey: "App key",
  },
  paypal: {
    title: "Paypal",
    secretKey: "Secret Key",
    siteId: "Site ID",
  },
  flutterwave: {
    title: "Flutterwave",
    secretKey: "Secret Key",
    appKey: "App key",
  },
  cinet: {
    title: "CINET",
    siteId: "Site Id",
    clientApiKey: "Client Api key",
    secretKey: "Secret Key",
  },
  sadad: {
    title: "SADAD",
    siteId: "Site Id",
    secretKey: "Secret Key",
    domain: "Domain",
  },
  airtelMoney: {
    title: "Airtel Money",
    siteId: "Site Id",
    secretKey: "Secret Key",
  },
  phonePe: {
    title: "PhonePay",
    appId: "AppID",
    merchantId: "MerchantID",
    saltId: "SaltID",
    saltKey: "SaltKey",
  },
  midtrans: {
    title: "Midtrans",
    siteId: "Site Id",
  },
  mercadopago: {
    title: "Mercadopago",
    publicKey: "Public Key",
  },
  xendit: {
    title: "Xendit",
    secretKey: "Secret Key",
    webhookToken: "Webhook Token",
  },
  cashfree: {
    title: "Cashfree",
    appId: "App ID",
    secretKey: "Secret Key",
  },
};

// stock 
export const createStockTransfer = "Stock Transfer added successfully.";
export const updateStockTransfer = "Stock Transfer added successfully.";

// Email Notification Templates
export const emailNotificationTemplatesHeading = "Email Notification Templates";
export const emailNotificationTemplatesBio = "Manage and customize email notification templates for your system";
export const emailTemplateTitle = "Email Template";
export const emailSubjectPlaceholder = "Enter email subject";
export const emailContentPlaceholder = "Enter email template content...";
export const emailTemplateSavedSuccess = "Email template saved successfully!";
export const emailTemplateDeletedSuccess = "Email template deleted successfully!";
export const emailStatusUpdateSuccess = "Email template status updated successfully!";
export const dynamicParametersLabel = "Dynamic Parameters";
export const selectRecipients = "Select recipients";
// roles and permissions
export const rolesPermissionStrings = {
  title: "Roles & Permissions",
  description: "Manage module permissions for different user roles",
  searchPlaceholder: "Search modules...",
  noResults: "No modules match your search query.",
  saveButton: "Save",
  moduleActionHeader: "Module / Action",
};

// Sales Management
export const salesManagement = "Sales Management";
export const addSales = "Add Sale";
export const editSales = "Edit Sale";
export const salesManagementDescription = "Manage your sales and orders";

export const BARCODE_CONSTANTS = {
  title: "Print Labels",
  scanDescription: "Scan product QR codes to retrieve product information and generate new barcodes and QR codes.",
  clearAll: "Clear All",
  printAll: "Print All",
  fontSize: "Font size",
  infoTitle: "Information to show in Labels",
  settingsTitle: "Barcode Settings & Product Overrides",
  searchPlaceholder: "Search product by name / SKU / barcode",
  createProduct: "Create Product",
  generate: "Generate",
  clear: "Clear",
  previewSelected: "Preview Selected",
};
export const defaultBarcodeSettings: AdminTypes.InventoryTypes.BarcodeTypes.BarcodeSettings = {
  format: 'CODE128',
  width: 2,
  height: 100,
  displayValue: true,
  fontSize: 20,
  margin: 10,
  background: '#ffffff',
  lineColor: '#000000',
  textAlign: 'center',
  textPosition: 'bottom',
  textMargin: 2,
};

export const RolesPermissionConstants = {
  permission: "Permission",
  modules: "Modules",
  view: "View",
  add: "Add",
  edit: "Edit",
  bulkUpdate: "Bulk Update",
  bulkDelete: "Bulk Delete",
  deleteLabel: "Delete"
}

