//Business Owner
export const ownerheading = "Business Owners"
export const ownerbio = "Centralized management for owner details, profiles, permissions, and system-wide operational control"
export const addOwner = "Add Owner"
export const editOwner = "Edit Owner"
export const ownername = "Business Owner Name"
export const phonelabel = "Phone No"
export const emaillabel = "Email"
export const passwordlabel = "Password"
export const businessnamelabel = "Business Name"
export const selectcategory = "Select Category"
export const businesscategorylabel = "Business Category"
export const statuslabel = "Status"
export const businessownerprofile = "Business Owner Profile"
export const businessownerprofilebio = "Complete business and owner information"
export const ownerinformation = "Owner Information"
export const fullnamelabel = "Full Name"
export const emailaddresslabel = "Email Address"
export const contactnumberlabel = "Contact Number"
export const genderlabel = "Gender"
export const lastloginlabel = "Last Login"
export const businessinformation = "Business Information"
export const categorylabel = "Category"
export const businessstatuslabel = "Business Status"
export const activitytimeline = "Activity Timeline"
export const createdonlabel = "Created On"
export const lastmodifiedlabel = "Last Modified"
export const categoryFilter = "All Categories"
export const saving = "Saving..."
export const save = "Save"

//Business Category
export const categoryheading = "Business Categories"
export const categorybio = "Organize businesses into categories for structured management, quick filtering, and insightful reporting"
export const addCategory = "Add Category"
export const editCategory = "Edit Category"
export const categoryname = "Category Name"
export const descriptionlabel = "Description"
export const max250characters = "Maximum 250 Characters"
export const max500characters = "Maximum 500 Characters"
export const max50characters = "Maximum 50 Characters"
export const businesscategorydetails = "Business Category Details"
export const businesscategorydetailsbio = "Complete category information"
export const categoryinformation = "Category Information"
export const additionaldetails = "Additional Details"
export const active = "Active"
export const inactive = "Inactive"

//Subscription
export const subscriptionheading = "Subscriptions"
export const subscriptionbio = "Monitor active subscriptions, billing cycles, renewals, and usage with streamlined subscription workflow"
export const addSubscription = "Add Subscription"
export const exportcsv = "Export CSV"
export const purchasedatelabel = "Purchase Date"
export const totalamountlabel = "Total Amount"
export const subscriptiondetails = "Subscription Details"
export const userinformation = "User Information"
export const name = "Name"
export const activeplans = "Active Plans"
export const pendingplans = "Pending Plans"
export const activesubscriptions = "Active Subscriptions"
export const lastpendingsubscription = "Last Pending Subscription"
export const durationlabel = "Duration"
export const storeslabel = "Stores"
export const userslabel = "Users"
export const moduleslabel = "Modules"
export const subscriptionnumber = "Subscription"
export const amountlabel = "Amount"
export const selectuser = "Select User"

//Plan
export const planheading = "Plan Management"
export const planbio = "Create, update, and customize pricing plans tailored to different business needs and growth stages"
export const allplans = "All Plans"
export const addplan = "Add Plan"
export const editplan = "Edit Plan"
export const paidplan = "Paid Plan"
export const freeplan = "Free Plan"
export const plannamelabel = "Plan Name"
export const plantypelabel = "Plan Type"
export const plandurationlabel = "Plan Duration"
export const planpricelabel = "Plan Price"
export const freeplanshaveafixedpriceof0 = "Free plans have a fixed price of $0"
export const discounttypecolabel = "Discount Type"
export const discountlabel = "Discount"
export const discount0to100 = "0 - 100%"
export const trialplanlabel = "Trial Plan"
export const markthisasatrialplan = "Mark this as a trial plan"
export const screenselectionlabel = "Screen Selection"
export const selectedscreens = "Selected screens:"
export const staffcountlabel = "Staff Count"
export const storecountlabel = "Store Count"
export const taxlabel = "Tax"
export const planmodulelabel = "Plan Modules"
export const totalpricelabel = "Total Price"
export const selectall = "Select All"
export const allmodules = "All Modules"
export const total = "Total"
export const modules = "Modules"
export const plandetails = "Plan Details"
export const completeplaninformation = "Complete plan information"
export const basicinformation = "Basic Information"
export const limitsandfeatures = "Limits & Features"

//Tax
export const taxheading = "Tax Management"
export const taxbio = "Configure and apply tax rules accurately across transactions to ensure compliance and reliability"
export const addTax = "Add Tax"
export const editTax = "Edit Tax"
export const taxtitlelabel = "Tax Title"
export const taxtypelabel = "Tax Type"
export const taxvaluelabel = "Tax Value"
export const taxdetails = "Tax Details"
export const taxdetailsbio = "Complete tax information"
export const taxinformation = "Tax Information"
export const taxname = "Tax Name"

//Coupon
export const couponheading = "Coupon Management"
export const couponbio = "Generate and manage discount coupons to increase sales engagement and attract repeat customers"
export const addcoupon = "Add Coupon"
export const editcoupon = "Edit Coupon"
export const couponcodelabel = "Coupon Code"
export const typelabel = "Type"
export const startdatelabel = "Start Date"
export const enddatelabel = "End Date"
export const discountamountlabel = "Discount Amount"
export const limitlabel = "Limit"
export const maxusageperuserlabel = "Max Usage Per User"
export const selectplanslabel = "Select Plans"
export const finalCoupon = "Coupon"
export const coupondetails = "Coupon Details"
export const coupondetailsbio = "Complete coupon information"
export const additionalinformation = "Additional Information"

//Advertisement
export const advertisementheading = "Advertisement Management"
export const advertisementbio = "Control promotional banners, marketing placements, and advertisement visibility for improved outreach"
export const addAdvertisement = "Add Advertisement"
export const editAdvertisement = "Edit Advertisement"
export const adnamelabel = "Ad Name"
export const selecttypelabel = "Select Type"
export const urltypelabel = "URL Type"
export const mediacontentlabel = "Media Content"
export const selectedlabel = "Selected"
export const placementlabel = "Placement"
export const positionlabel = "Position"
export const redirecturllabel = "Redirect URL"
export const advertisementdetails = "Advertisement Details"
export const advertisementdetailsbio = "Complete advertisement information"
export const advertisementidlabel = "Advertisement ID"
export const localmedialabel = "Local Media"
export const fileuploadedlocallylabel = "File uploaded locally"

//dashboard
export const bannerheading = "Welcome Back, Super Admin"
export const bannerbio = "14 New Business Owners Subscribed Today !!!"
export const insights = "Insights"
export const generatereport = "Generate Report"
export const revenueoverview = "Revenue Overview"
export const planwisesubscriptions = "Plan-wise Subscriptions"
export const businessbyregion = "Business by Region"
export const subscriptiontrends = "Subscription Trends"


//settings
export const settingsheading = "Settings"
export const settingsbio = "Manage your application settings"
export const general = "General"
export const misc = "Misc"
export const mail = "Mail"
export const integration = "Integration"
export const currency = "Currency"
export const payment = "Payment"
export const language = "Language"
export const invoice = "Invoice"
export const templates = "Templates"
export const trial = "Trial"
export const gdpr = "GDPR"
export const seo = "SEO"
export const businesssettings = "Business Settings"
export const minilogo = "Mini Logo"
export const logo = "Logo"
export const darklogo = "Dark Logo"
export const lightlogo = "Light Logo"
export const favicon = "Favicon"
export const savegeneralsettings = "Save General Settings"
export const enabledarkmode = "Enable Dark Mode"
export const allowusertoggledarkmode = "Allow users to toggle dark mode"
export const maintenancemode = "Maintenance Mode"
export const maintenancemodebio = "Put the site in maintenance mode"
export const savemiscsettings = "Save Misc Settings"
export const timezone = "Timezone"
export const datatablelimits = "DataTable Limits"
export const subscriptionexpiryalert = "Subscription Expiry Alert (Days)"
export const dateformat = "Date Format"
export const timeformat = "Time Format"
export const savemailsettings = "Save Mail Settings"
export const mailfrom = "Mail From"
export const fromname = "From Name"
export const smtphost = "SMTP Host"
export const smtpport = "SMTP Port"
export const smtpusername = "SMTP Username"
export const smtppassword = "SMTP Password"
export const smtpencryption = "SMTP Encryption"
export const maildriver = "Mail Driver"
export const testconnection = "Test Connection"
export const verify = "Verify"
export const settingsverified = "Settings Verified"
export const settingsnotverified = "Settings Not Verified"
export const lastverified = "Last Verified"
export const connectiontested = "Connection Tested"
export const connectionfailed = "Connection Failed"
export const mailsettingssaved = "Mail settings saved successfully"
export const mailsettingserror = "Error saving mail settings"
export const testconnectionerror = "Error testing connection"
export const verificationsuccess = "Settings verified successfully"
export const verificationerror = "Error verifying settings"
export const saveintegrationsettings = "Save Integration Settings"
export const googlelogin = "Google Login"
export const demologin = "Demo Login"
export const customwebhooknotification = "Custom Webhook Notification"
export const googlemapskey = "Google Maps"
export const secretkey = "Secret Key *"
export const publickey = "Public Key *"
export const contentkey = "Content Key *"
export const url = "URL *"
export const googleappskey = "Google Apps Key *"
export const savecurrencysettings = "Save Currency Settings"
export const savepaymentsettings = "Save Payment Settings"
export const savelanguagesettings = "Save Language Settings"
export const saveinvoicesettings = "Save Invoice Settings"
export const savetemplatessettings = "Save Templates Settings"
export const savetrialsettings = "Save Trial Settings"
export const savegdprsettings = "Save GDPR Settings"
export const saveseosettings = "Save SEO Settings"
export const addnewcurrency = "+ Add New Currency"
export const viewintegration = "View Integration"
export const includetermsandconditions = "Include Terms & Conditions"
export const emailtemplates = "Email Templates"
export const smstemplates = "SMS Templates"
export const enablegdprcookienotice = "Enable GDPR Cookie Notice"
export const enablegdprbio = "Show cookie consent banner to users"
export const currencyasprimary = "currency is selected as primary"
export const cookiemessage = "Cookie Message"
export const currentlypositionlabel = "Currency Position *"


//business owner reports
export const businessownerreportheading = "Business Owner Reports"
export const businessownerreportbio = "View and export business owner subscription reports"

//commission reports
export const commissionreportheading = "Commission Reports"
export const commissionreportbio = "View and export commission reports"
export const summary = "Summary"
export const totaltransactions = "Total Transactions"
export const totaltransactionamount = "Total Transaction Amount"
export const totalcommissionamount = "Total Commission Earned"
export const averagecommissionpercentage = "Average Commission %"

export const description = "Description"
export const shortdescriptionlabel = "Short Description *"
export const shortdescription = "Short Description"
export const allstatus = "All Status"
export const activestatus = "Active"
export const inactivestatus = "Inactive"
export const pendingstatus = "Pending"
export const alltypes = "All Types"
export const fixed = "Fixed"
export const percentage = "Percentage"
export const phone = "Phone Number"
export const email = "Email"
export const password = "Password"
export const cancelbutton = "Cancel"
export const closebutton = "Close"
export const startdate = "Start Date"
export const enddate = "End Date"
export const createddate = "Created Date"
export const lastupdated = "Last Updated"
export const saveallchanges = "Save All Changes"
export const upload = "Upload"
export const actionLabel = "Actions"
export const templateStatus = "Status"




// Landing Page Settings (Super Admin)
export const landingpageheading = "Landing Page Settings"

// Tabs
export const tabHero = "Hero"
export const tabBusinessTypes = "Business Types"
export const tabFeatures = "Features"
export const tabProductOverview = "Product Overview"
export const tabFAQCategory = "FAQ Category"
export const tabPricing = "Pricing"
export const tabFAQ = "FAQ"
export const tabBlog = "Blog"
export const tabCTA = "CTA"
export const tabFooter = "Footer"
export const tabSocialMedia = "Social Media"

// Common labels
export const add = "Add"
export const back = "Back"
export const titlelabel = "Title"
export const subtitlelabel = "Subtitle"
export const ctatextlabel = "CTA Text"
export const ctalinklabel = "CTA Link"
export const backgroundimagelabel = "Background Image"
export const heroimagelabel = "Hero Image"
export const imagelabel = "Image"
export const bgcolorlabel = "BG Color"
export const actions = "Actions"
export const newlabel = "New"
export const retry = "Retry"
export const removelabel = "Remove"
export const savechanges = "Save Changes"
export const question = "Question"
export const answer = "Answer"
export const requiredstar = "*"
export const deleteLabel = "Delete"

// Sections
export const herosection = "Hero Section"
export const businesstypessection = "Perfect for Every Business Type"
export const featuressection = "Features Section"
export const productoverviewsection = "Product Overview Section"
export const faqcategorysection = "FAQ Category Section"
export const pricingsection = "Pricing Section"
export const ctasection = "CTA Section"
export const footersection = "Footer Section"

// Features & product overview
export const featureslabel = "Features"
export const addfeature = "Add Feature"
export const dashboardcardslabel = "Dashboard Cards"
export const adddashboard = "Add Dashboard"
export const dashboardimagelabel = "Dashboard Image"

// Business types
export const businessTypeHeading = "Business Types"
export const sectiontitlelabel = "Section Title"
export const sectiondescriptionlabel = "Section Description"
export const businesstypeslabel = "Business Types"
export const iconlabel = "Icon"

// CTA
export const benefitslabel = "Benefits"
export const addbenefit = "Add Benefit"

// Footer
export const footerdescriptionlabel = "Footer Description"
export const productlinkslabel = "Product Links"
export const companylinkslabel = "Company Links"
export const addproductlink = "Add Product Link"
export const addcompanylink = "Add Company Link"

// FAQ
export const faqheading = "FAQ"
export const loadingfaqs = "Loading FAQs..."
export const errorloadingfaqs = "Error loading FAQs:"
export const nofaqsfound = "No FAQs found. Create your first FAQ to get started."
export const faqcreated = "FAQ created successfully!"
export const faqupdated = "FAQ updated successfully!"
export const faqdeleted = "FAQ deleted successfully!"
export const faqsaverror = "Error saving FAQ:"
export const faqupdateerror = "Error updating FAQ status:"
export const faqdeleteerror = "Error deleting FAQ:"
export const faqdeleteconfirmtitle = "Delete FAQ"
export const faqdeleteconfirmtext = "Are you sure you want to delete this FAQ? You won't be able to revert this!"


// Notification Templates
export const notificationTemplatesHeading = "Notification Templates"
export const notificationTemplatesBio = "Manage and customize notification templates for your system"
export const addTemplate = "Add Template"
export const editTemplateConstant = "Edit Template"
export const templateLabel = "Label"
export const templateType = "Type"
export const templateUserType = "User type"
export const toLabel = "To"
export const notificationTemplateTitle = "Notification Template"
export const emailTemplateTitle = "Email Template"
export const subjectLabel = "Subject"
export const contentTemplateLabel = "Content Template"
export const dynamicParametersLabel = "Parameters"
export const templateSavedSuccess = "Template saved successfully."
export const templateDeletedSuccess = "Template deleted successfully."
export const templateDeletedConfirmTitle = "Are you sure?"
export const templateDeletedConfirmText = "You want to delete this template?"
export const selectTemplateType = "Select type"
export const selectUserType = "Select user type"

// Template Types
export const typeChangePassword = "Change Password"
export const typeCancelSubscription = "Cancel Subscription"
export const typeNewSubscription = "New Subscription"
export const typeVendorRegistered = "Vendor Registration"
export const typePurchasePlan = "Plan Purchase"
export const typeForgetPassword = "Forget Email/Password"

// User Types
export const userTypeVendor = "Vendor"
export const userTypeCustomer = "Customer"
export const userTypeUser = "User"
export const userTypeAdmin = "Admin"
export const userTypeManager = "Manager"
export const userTypeSupplier = "Supplier"
export const userTypeSuperadmin = "Super Admin"
export const selectTo = "Select recipients"

// Notification List
export const notificationHeading = "Notifications"
export const notificationBio = "Manage and view all notifications"
export const filterAll = "All"
export const filterUnread = "Unread"
export const filterRead = "Read"
export const markAsUnreadLabel = "Mark as unread"
export const markAsReadLabel = "Mark as read"
export const markAllAsReadLabel = "Mark all as read"
export const deleteAllLabel = "Delete All"
export const selectedLabelCount = "selected"
export const fromLabel = "From:"
export const noNotificationsFound = "No notifications found."
export const enterNotificationSubjectPlaceholder = "Enter notification subject"
export const enterNotificationContentPlaceholder = "Enter notification template content..."
export const enterEmailSubjectPlaceholder = "Enter email subject"
export const enterEmailContentPlaceholder = "Enter email template content..."

// Notification List - Column Names
export const senderColumnLabel = "Sender"
export const notificationColumnLabel = "Notification"
export const dateColumnLabel = "Date"
export const subjectColumnLabel = "Subject"
export const messageColumnLabel = "Message"

// Notification List - Detail View
export const backAriaLabel = "Back"
export const deleteAriaLabel = "Delete"

// Notification Templates - Status & Filters
export const allStatusFilter = "All"
export const activeStatusFilter = "Active"
export const inactiveStatusFilter = "Inactive"
export const statusActionOption = "Status"
export const deleteActionOption = "Delete"

// Notification Templates - User Types
export const userTypeLabel = "User Type"

// Notification Templates - Messages
export const bulkActionsNotImplemented = "Bulk actions for notifications are not yet implemented."
export const templateValidationError = "Please provide both Subject and Content for at least one template (Notification or Email)."
export const templateSaveError = "Failed to save template."
export const statusUpdateSuccess = "Status updated successfully."
export const statusUpdateError = "Failed to update status."
export const templateDeleteError = "Failed to delete template."

// Notification Popup
export const notificationsHeader = "Notifications"
export const markAsReadButton = "Mark as read"
export const loadingNotifications = "Loading..."
export const noNotificationsYet = "No notifications yet"
export const viewAllButton = "View All"
export const justNow = "Just now"
export const minutesAgo = "m ago"
export const hoursAgo = "h ago"
export const daysAgo = "d ago"

// Notification Popup - Dummy Data (can be removed when real API is connected)
export const dummyNotificationTitle1 = "New User Registration"
export const dummyNotificationMessage1 = "A new user has registered on your platform. Please review their profile."
export const dummyNotificationTitle2 = "System Update Available"
export const dummyNotificationMessage2 = "A new system update is available. Please review the changes."
export const dummyNotificationTitle3 = "Payment Received"
export const dummyNotificationMessage3 = "Payment of $99.99 has been received from customer John Doe."

// Days of Week
export const sunday = "Sunday"
export const monday = "Monday"
export const tuesday = "Tuesday"
export const wednesday = "Wednesday"
export const thursday = "Thursday"
export const friday = "Friday"
export const saturday = "Saturday"