"use client";
import { makeLazy } from "./lazy";
export const StockAdjustmentsLazy = makeLazy(() => import("@/components/admin/stock/StockAdjustments"));
export const StockTransfersLazy = makeLazy(() => import("@/components/admin/stock/StockTransfers"));
export const PurchaseOrderManagementLazy = makeLazy(() => import("@/components/admin/purchase/PurchaseOrderManagement"));
export const LeaveManagementLazy = makeLazy(() => import("@/components/admin/hrm/LeaveManagement"));
export const ProductsLazy = makeLazy(() => import("@/components/admin/inventory/products"));
export const CustomerManagementLazy = makeLazy(() => import("@/components/admin/people/CustomerManagement"));
export const CouponManagementLazy = makeLazy(() => import("@/components/admin/promo/CouponManagement"));
export const GiftCardConfigLazy = makeLazy(() => import("@/components/admin/promo/GiftCardConfig"));
export const TaxManagementLazy = makeLazy(() => import("@/components/admin/finance/TaxManagement"));
export const AttendanceLazy = makeLazy(() => import("@/components/admin/hrm/Attendance"));
// export const Pos1Lazy = makeLazy(() => import("@/components/admin/pos-screen/pos-1"));
export const SalesReportLazy = makeLazy(() => import("@/components/admin/reports/SalesReport"));
export const HolidayManagementLazy = makeLazy(() => import("@/components/admin/hrm/HolidayManagement"));
export const LeaveTypeManagementLazy = makeLazy(() => import("@/components/admin/hrm/LeaveTypeManagement"));
export const ShiftManagementLazy = makeLazy(() => import("@/components/admin/hrm/ShiftManagement"));
// export const ShiftAssignmentLazy = makeLazy(() => import("@/components/admin/hrm/ShiftAssignment"));
export const StaffManagementLazy = makeLazy(() => import("@/components/admin/hrm/StaffManagement"));
export const PayrollManagementLazy = makeLazy(() => import("@/components/admin/hrm/PayrollManagement"));
// export const HRMDashboardLazy = makeLazy(() => import("@/components/admin/hrm/HRMDashboard"));

export const SuperadminDashboardLazy = makeLazy(() => import("@/components/superadmin/dashboard/dashboard"));
export const SuperadminSettingsLazy = makeLazy(() => import("@/components/superadmin/settings/settings"));
export const SuperadminPlansLazy = makeLazy(() => import("@/components/superadmin/plan/plans"));
export const SuperadminTaxLazy = makeLazy(() => import("@/components/superadmin/tax/tax"));
export const SuperadminSubscriptionLazy = makeLazy(() => import("@/components/superadmin/subscription/subscription"));
export const SuperadminBusinessOwnerLazy = makeLazy(() => import("@/components/superadmin/business-owner/business-owner"));
export const SuperadminBusinessCategoryLazy = makeLazy(() => import("@/components/superadmin/business-category/business-category"));
export const SuperadminAdvertisementLazy = makeLazy(() => import("@/components/superadmin/advertisement/advertisement"));
export const SuperadminCouponLazy = makeLazy(() => import("@/components/superadmin/coupon/coupon"));
export const SuperadminLandingPageSettingsLazy = makeLazy(() => import("@/components/superadmin/landingpage-settings/landingpage-setting"));
export const SuperadminNotificationTemplatesLazy = makeLazy(() => import("@/components/superadmin/notifications/NotificationTemplates"));
